var exampleLevels=[
  [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@       @",
    "@@@@@@@@@@@@@@@@@@@        eeeeeeee@@@      +@",
    "@@@@@@@@@@@@@@@@@@@        effffffe@@@      @@",
    "@@@@@@@@@@@@@@@@@@@        @@@@@@@e@@@      @@",
    "@#########@@@L             @@@@@L  R@@      @@",
    "@###eeee##@@@@>eee<vw      @@@@@L  R@@      @@",
    "@##e    ee@@@@#eeeR@w     p@@@@@L  R@@      @@",
    "@#e       @@@@Leee#@w      @@@@@L  R@@      @@",
    "@e  f^@ww#@@@@#eeeR@w      @@@@@L  R@@      @@",
    "@   #@@&ww@@@@L   R@w      @@@@@L  R@@      @@",
    "@   #@@ww#@@@@L    Raw# # #@@@@@L  R@@      @@",
    "@    @@&ww@@@@L&  R@ww# # #@@@@@L  R@@      @@",
    "@^   @@www@@@@L    Rww# # #@@@@@L  R@@      @@",
    "@#   @@w&w@@@@L   R@ww# # #@@@@@L  R@@      @@",
    "@    @@##w@@@@L  &@@ww# # #@@@@@L  R@@      @@",
    "@   ^@@www@@@@L   R@ww# # #@@@@@L  R@@      @@",
    "@   #@@www@@@@L    Rww# # #@@@@@L  R@@      @@",
    "@    @@w&w@@@@L&  R@ww# # #@@@@@L  R@@      @@",
    "@    @@w##@@@@L    Rww# # #@@@@@L  R@@      @@",
    "@^   @wwww@@@@L   R@ww# # #@@@@@L  R@@      @@",
    "@#   @ww##@@@@L  &@@ww# # #@@@@@L  R@@      @@",
    "@    #    @####   R@ww# # #@       R@@      @@",
    "@    #   #L       #@ww# # #@aaaa<  R## Ciiii@@",
    "@    #            #@a@#p#p#@@@@@@      #@@@@@@",
    "@v^^^@Cv*<><>*v^BB@@@@@@@@@@@@@@@@@>####@@@@@@"
  ],"Untitled-0"," Steven",
  [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@**              @        @ ####@",
    "@**              @      @;@+####@",
    "@**  @@@@@@@@@@;;       @@ +    @",
    "@**           @@@@ii@@@ @@ +aaa @",
    "@**           @@@   @@@ @@  ### @",
    "@**p@@>>>@m   @@@  t@@@ @@  ### @",
    "@**@@@@@@@@   @@@  @@@@p@@      @",
    "@  ########   @@@  @        ### @",
    "@  ########   *ww  @        ### @",
    "@             *ww  @        ### @",
    "@@@aa######@pp@@@ii@oo@@@@@@@@@p@"
  ],"Untitled-0"," Zach",
  [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@   *******    ss  #### wwww@    @g    @",
    "@   wwwwwww        #### @@@w@ @;;@g    @",
    "@   w#####w           # @+@w@ @***g    @",
    "@   wwwwwww    vv     # @+@w@ @***g    @",
    "@   ww####w    ##       @ @w@ @***g    @",
    "@   wwwwwww    ##       @ @ww @***g    @",
    "@   w#####w    ##       @ @@@i@***g    @",
    "@   wwwwwww    ##       @ ********g    @",
    "@ >>*******^^^^##ggg&ggp@         g    @",
    "@@@@@@@@@@@@@@@@@@@@@@@@@p@@@@@@@@@@@@@@"
  ],"Untitled-1"," Zach",
  [[{}],
    "ááááááááááááááá+á",
    "áááááááááááááááíá",
    "á      L   L   yá",
    "á      L >   **tá",
    "á      óy>>>&   á",
    "á  Lúóóóyý      á",
    "L    >>>        á",
    "áa>>Báááááááááááá"
  ],"Recursive Death"," Sean",
  [[{}],
    "@@@@@",
    "Ly  g",
    "ýy>;ý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "@yágý",
    "@ ágý",
    "@&á+@"
  ],"Slammer"," Sean",
    [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "+ááááááá      u u u   uuuuuuuu@",
    "+ááááááá      u   u u uuuuuuuu@",
    "+             u u u    u u u u@",
    "+íí  í í @úúú@uuuuuuuuuuuuuuuu@",
    "@@@@@@@@@@@ó@@@@@@@@@@@@@@@@@ @",
    "L    L    á á               q @",
    "L  L L L                    q @",
    "L  L   L á á á                @",
    "BBBB>>B@@@@@@@@@@@@@@@>>>#a#<@@"
  ],"Untitled-0"," ANONYMOUS",
  [[{}],
    "************",
    "*yyyyyyyy*+*",
    "*yyyiyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "********p***"
  ],"Teh Bleu Levle"," Sean",
  [[{},"Welcome to the factory"],
    "`||||||||`",
    "LR||LLRee+",
    "LeeR||ReRR",
    "LBeee|eeeR",
    "LReLeeeReR",
    "LeeeLReBeR",
    "LeReeeBeeR",
    "LeBR|eeeRR",
    "LeRLBRLeeR",
    "`0BBBBBBB`"
  ],"Factoyr"," Sean",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@############################",
    "@w   w    +@     íqyqq    ###",
    "@  w   ww@@@ í    qyqq     ##",
    "@ @@@@m@@         qqqq     *#",
    "@  w w            qqqq      #",
    "@^       @ @   == qqyq      #",
    "@      @@###@@    qqyq  C*  #",
    "@##* @@||#||#|ééé**@@@&&@   #",
    "@@@@@ywyywwwwwuuuuuuíuuu@  *#",
    "@ @# ywwwwyyyyuuíuuuuuuu@*  #",
    "@ @# yyyyyywwwuuuuuuuuuuL   #",
    "@    wwwwwwwyyuuuuuuuuuu    #",
    "@C***&&&&&&&&&@@@@@@@@@@@@&&@"
  ],"a level - remake"," Anonymous",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@óóóóyyyyyy@@@@@@@@@@óóó@@@@@@@@",
    "@                   íí  úúúuuwwu@",
    "@ C@@@@@ó@@@<@<@<ó     úúuuuwwu+@",
    "@                í@  úúúuuwww@@@@",
    "@    f@@ó@ó@f     @@@@qnnníííííí@",
    "@&@@@@íííííí@@@   @www    í     @",
    "ó    qqnqqnqqn    @wíw          @",
    "@   qnnqnnqnn    óáwíw    vv vve@",
    "@ @@@@@@@@@@<@<@@ áwíw   íí ## e@",
    "@ yuyuyuyuy       áwíw   í  ## e@",
    "@||||@@@yuy       qwíw      ##  @",
    "L      íéééC@@@@@@@*í***>>>>@@  @",
    "L   R uuuuuíuuuuuuyyíywwwwyywwC R",
    "L  R#íuuuuíuuuuuyyyywwyyyywwyyu @",
    "L  R#fuuuuuíuuyyywwwyyywwwyyyuu @",
    "L  @##íuuuuuuyywwwyyywwwyyíuuuu @",
    "@@C@@@@@@@@@@@@@@@@@@@@@@@@@@@@&@"
  ],"another level","Anonymous",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@óóóó            @@@@        á  í  @",
    "@+á@@ @@nnnnnn@@      @@@@@@ó@@ @@ @",
    "@áá   @ áíííííá@@@ @@@óóóó@@ó@e @@ @",
    "@í@@@ @ @nnnn@áe@@ @@   @óóóó@e@@@ @",
    "@ @@@   @####@@e@@ííáá@ @@@@@@e @@ @",
    "@ @@@óóó@@@@@@@e@@@óó@@ @@@@@@@ @@ @",
    "@            @@eáá @óóó         @@ @",
    "@&@@@@@@@@@  á@@@@ @@@@@á@@@@@@e@@ @",
    "@uúuuúuyy@é @ááá@@     @í@@www@e@@ @",
    "@w@@@@@@y@@ @@@á@@ @ @ @ @@w#w@e@@ @",
    "@w@      @    @á@@ @ @ @ @@w#w@e@@ @",
    "@w@ @@@@@@    @á@@ @ @ @ @@w#w@e@@ @",
    "@ó@     @@ ^@ó@á@@ @ @     w#w e@@ @",
    "ó  @@@@ @@ @@ó@á@@ @ @@@^@@@@@@@@@ @",
    "ó  áááá    @@óó    @               @",
    "@@C@@@@@@@^@@@@@@@p@@@@@@@@@@@@@@@i@"
  ],"maze","Anonymous",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@   @   @   @        @ @ @ @ @   +@",
    "@ @   @   @ @ ######t@@@@@@@@@m@@@@",
    "@ @@@@@@@@@ @ #     @@@@@@@@@@@@@@@",
    "@ @         @         á   á   á  y@",
    "@ @;@@@@@@@@@p     iá á á á á á @y@",
    "@ @@ý@e  @@@@@#####@á   á   á   @y@",
    "@ @@ý@e@         @@@áááááááááááá@y@",
    "@ @@ý@e@@a#####@ @@@@@@@@@@@@@@@@y@",
    "@ @@ý@e@@@@@@@@@ @www@www@www@wwww@",
    "@ @@ý@e@         @w#w@w#w@w#w@w#@@@",
    "@ @@ý@e@ @@@@@@@@@w#w@w#w@w#w@w#@@@",
    "@ @@ý@e@ @   @   @w#w@w#w@w#w@w#@@@",
    "@ @  @e@ @ @ @ @ @w#w@w#w@w#w@w#@@@",
    "@ @@ @e@ @ @ @ @ @w#w@w#w@w#w@w#@@@",
    "@  @   @   @   @  w#w w#w w#w w#@@@",
    "@@C@@@@@@@@@@@@@@C@@@C@@@C@@@@@@@@@"
  ],"training level","Anonymous",
  [[{},"Feel free to add in another Lava to Solid Powerup"],
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@óóóóó",
    "@@@@@@@@@@óóóóóóóóóóóóóóóóóóóóóóóóóóó@@@@@@@@@óóóóó",
    "@@@@@@@@@@óó@@@@@@@@@@@@@@@@@@@@@@@@óó       @óóóóó",
    "@@@@@@@@@@@ó@@@@@@@        eeeeeeee@@@      +@óóóóó",
    "@@@@@@@@@@@ó@@@@@@@        effffffe@@@      @@óóóóó",
    "@@@@@@@@@@@ó@@@@@@@        @@@@@@@e@@@ q    @@óóóóó",
    "@#########@ó@Luuuuuu       @@@@@LhhR@@ qqq  @@óóóóó",
    "@###eeee##@ó@@>eee<vw      @@@@@LuuR@@      @@óóóóó",
    "@##e    ee@ó@@#eeeR@w     p@@@@@LuuR@@ q  q @@óóóóó",
    "@#e       @óó@Leee#@w      @@@@@LuuR@@ qqqqq@@óóóóó",
    "@e  f^@ww#@@ó@#eeeR@w      @@@@@LuuR@@ qqqqq@@óóóóó",
    "@   #@@&ww@@ó@L   R@w      @@@@@LuuR@@ qq q @@óóóóó",
    "@   #@@ww#@@ó@L    Raw# # #@@@@@LuuR@@  qq  @@óóóóó",
    "@    @@&ww@@ó@L&  R@ww# # #@@@@@LuuR@@ q    @@óóóóó",
    "@^   @@www@@ó@L    Rww# # #@@@@@LuuR@@ qqqq @@óóóóó",
    "@#   @@w&w@@ó@L   R@ww#w#w#@@@@@LuuR@@ qq   @@óóóóó",
    "@    @@##w@@ó@L  &@@ww#w#w#@@@@@LuuR@@ qq   @@óóóóó",
    "@   ^@@www@@ó@L   R@ww# # úó@@@@LuuR@@ qqqq @@óóóóó",
    "@   #@@www@@ó@L    Rww# # #óó@@@LuuR@@   qq @@óóóóó",
    "@    @@w&w@@ó@L&  R@ww# # #@óó@@LuuR@@ qq q @@óóóóó",
    "@    @@w##@@ó@L    Rww# # #@@óó@LuuR@@  qq  @@óóóóó",
    "@^   @wwwwóóó@L   R@ww# # #@@@óóLuuR@@     p@@óóóóó",
    "@#   @ww##@@@@L  &@@ww# # #@@@@óL  R@@    p#@@óóóóó",
    "@    ú    @####   R@ww# # #@       R@@   p##@@óóóóó",
    "@    #   #L       #@ww# # #@maaa<  R## Ci###@@óóóóó",
    "@    #            #@a0#p#p#@@@@@@      #@@@@@@óóóóó",
    "@v^^^@Cv*<><>*v^BB@@@@@@@@@@@@@@@@@>####@@@@@@óóóóó"
  ],"Untitled-0 by Steven (Revised)","Ben",
  // Updated once again 2020-12-01
  [[{"cpx":80,"cpy":80},"Hello world!","At this point guess."],
    "                                                     gddd     #     #        @@@",
    "                                                     g+dd  #  d  #  d        wwR",
    "                                                     ggggggggv=gggvg=ggggCgggyy@",
    "                                                     ggggggggggggggggggggggggyy@",
    "                                                                            gqq@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                        f                                                   gyy@",
    "                       f#f                                                  gyy@",
    "                       ###                                                  gyy@",
    "                       ###                                                  gyy@",
    "                       @@@                                                  gyy@",
    "s                     @f@f@                                                 gyy@",
    "s                      @@@                                                  gyy@",
    "s                    ww @                                                   gyy@",
    "s                    ww @@                  á                               gyy@",
    "s                    ww @@                  á                               gyy@",
    "s                    ww @@@          ó      á                               gyy@",
    "s                    ww @@@@                á                               gyy@",
    "syy      m;=f        ww @@@@                á                               gyy@",
    "sww============      ww @@@@         d      á                               gyy@",
    "swwwssssssssss|      ww @@@@         d      á                               gyy@",
    "swwwssssLwwwwww      ww @@@@@        d      |á                              gyy@",
    "sswsssssswwBBww      ww óóóóó        d       á                              gyy@",
    "swwsssssswRwwLw      ww @@@@@        d       á                              gyy@",
    "swwsssssswwwCww      ww @fff@ggggggggwwwwwww á                              gyy@",
    "sw&sssssswwwwwwR     ww @=e=@gggggggg      L á                              gyy@",
    "sw ssssssBssssssssssssssssesssss@    ááááááL á                              gyy@",
    "sw sssssssssssssssssssssssesssss@          L á                              gyy@",
    "sw                        esssss@            á                              gyy@",
    "sw                        esssss@            á                              gyy@",
    "sw                         *####@            á                              gyy@",
    "s&***<<<<<<<<<<<<<<<<<<<<< *####@ #@#@#@#@#@C                               gyy@",
    "ggggggggggggggggggggggggg*e*####@wwuwuwuwuww@                               gyy@",
    "ggggggggggggggggggggggggg*e*####@C@@@@@@@@@ @                               gyy@",
    "ggggggggggggggggggggggggg*e*####@           @                               gyy@",
    "ggggggggggggggggggggggggg*e*####@           @                               gyy@",
    "ggggggggggggggggggggggggg*e*####@@ó@ó@ó@ó@1C@                               gyy@",
    "ggggggggggggggggggffggggg*e*####@@ @í@í@í@@@@                               gyy@",
    "@@@@@@@@@@@@@@@@@+@@#####*e*####@@ @ @ @ @@@@                               gyy@",
    "@wwwwwwwwwww   @@|@@#####*e*####@@ @ @ @ @@@@                               gyy@",
    "@wwwwwwwwwww ;  www@aaaaaae*####@@uuuuuuuóóóó                               gyy@",
    "@wwwwwwwwwwwww wwwwwwwwwwwe*####@@uuuuuuuáááá                               gyy@",
    "@wwwwwwwwwwwwwwwwwwCaaaaaa**####@@Chhhhhh@@@@                                yy@",
    "@wwwwwwwwwwwwww@w@@@############@@@@@@@@@@@@@yyyy       p                    yy@",
    "@wwwwwwwwww;;**@@@@@############@@@@@@@@@@@@@gggg******************************@"
  ],"A level... (updated once again)","230141",
  [[{"cpx":80,"cpy":80},"lava ahead!"],
    "@##@@@@@@@@@@@@@@+@@",
    "#        wwwww @@w@@",
    "+        wwwww  w@w@",
    "@##v#a=  wwwwi  w@w@",
    "@ @      wwwww  www@",
    "@        íííííh;Cp^@",
    "@B@@@@a>0@@@@@@@@@@@"
  ],"training level","sysdl132",
  [[{"cpx":80,"cpy":80},"flappyball","1","2","3","4","finish"],
    " #                #     #   #          +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #         #          +",
    " f                          #          +",
    " @                          #          +",
    "+@      &                   #           ",
    "+@     &#               #   #           ",
    "+@    &##         #     #  ^#           ",
    "+@   &###        @@ 1 @@ 2@@ C3gg       ",
    "+@  &####a     @@#@hhCh            gg5 &",
    "+@@&#######v0vC###@###################gg"
  ],"flappyball changed","sysdl132",
  [[{},"answer 2 questions to pass!(confusion)","q1:1+1=?","left=2;right=4","q2:apple+penx2+pineapple=?","left=PPAP;right=I don't know.","you win!","null","null","null","correct!"],
    "@*******@",
    "@wuuuuuu@",
    "@wC01h2h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@ óó@#@",
    "@w@ óó@#@",
    "@w@ 39@@@",
    "@w@     @",
    "@w@4hCh@@",
    "@w@@h@h@@",
    "@w@@h@h@@",
    "@w@@h@h@@",
    "@w@@h@h@@",
    "@w@óó@ff@",
    "@w@ó9@@@@",
    "@w@ó  @@@",
    "@w@@ C@@@",
    "@w@@    @",
    "@w@@a## @",
    "@w@     @",
    "@w@ ####@",
    "@w@    +@",
    "@&@5Cggv@"
  ],"questions for you!","sysdl132",
  [[{"SHEEPphys":"solid"},"welcome and watch out,if you want die,<<<","go down","go>>>(<<<checkpoint,next checkpoint 30 blocks away)","go up","<<<go","go down[!!!no more checkpoints!!!]","go down!!","jump!","<<<you win!","<<<"],
    "f@@@@@@@g@@@gggóóóóóóó      íg     ",
    "#      @ggg@g@gó@@@@@@@4á    g4h   ",
    "g      @g@g@gggó@@@@@@@      g     ",
    "g      @@@@@@@g       @   ááág  hh ",
    "g      ó    @@@       @      g     ",
    "gwwwwwww@@@  @@C56a## @áá    ghh   ",
    "gwwwwww@@@@o @@       @      g     ",
    "gw@1@@í@e##@ @@     97@á     g     ",
    "gw@@@@í@e#@@ @@       @ehhhó@gggggg",
    "gw@@@  @eú@@ @@       @e@@óó@gggagg",
    "gw@@@  @e@@@ @@ff+8fff@e@@ó^@gggggg",
    "gó@@@  @e@@@ @@@@@@@@@@e@@ó@@gg^ggg",
    "ó  áá   eíí        óó  e     gggggg",
    "`0C@@***@@@C2*@><@t@@@3@@@^@@gggggg"
  ],"level delier","132",
  [[{"cpx":80,"cpy":80,"SHEEPphys":"solid"},"Hello world!","Treasure area"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@                          @                              eR@",
    "@                          @                              eR@",
    "@                          @;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@e@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @nnnnnnnnnnnnnnnnnnnnnnnnnnnnn@y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @                             @y@@",
    "@                          @      sss ssss              <@y@@",
    "@                          @>sssssssssssssssssssssss   <@@y@@",
    "@                          @@>ssssssssssss s sss ssssss@@@y@@",
    "@                          @@@sssssssssssssss  s@@   s<@@@y@@",
    "@                          @@@>sssssssssssssssss@ ss  @@@@y@@",
    "@                          @@@@>ssss ssssssss `s@s @ <@@@@y@@",
    "@                          @@@@@sssssssgssssss`s@@@ <@@@@@y@@",
    "@                          @@@@@>s*sssg g g ss`ss@@<@@@@@@y@@",
    "@                          @@@@@@ *ssgggg gdg `sss @@@@@@@y@@",
    "@                          @@@@@@s``dddssggs *` sss@@@@@@@y@@",
    "@                          @vvvv@s`g   **** ssg* s @vvvvv@y@@",
    "@                          @vvvv@;;;;;;;;;;;;;;;;;;@vvvvv@y@@",
    "@                          @vvvv@sd g* g*** sss ggg@vvvvv@y@@",
    "@                          @vvvv@s d ***``*sss*ggs @vvvvv@y@@",
    "@                          @vvvv@s@@d **` *s*  gssg@vvvvv@y@@",
    "@                          @vvvv@s @d g*`*ss ss gs @vvvvv@y@@",
    "@                          @vvvv@ss @ss dg ss ddd@@@vvvvv@y@@",
    "@                          @vvvv@ssdssssg dgdgddd@@@vvvvv@y@@",
    "@                          @vvvv@sd`sss ssgg   gd@@@vvvvv@y@@",
    "@                          @vvvv@sd``*`**g g gsss  @vvvvv@y@@",
    "@                          @@@@@@@;;;;;;;;;;;;;;;;@@@@@@@@y@@",
    "@                          @#####@ ds*``sgs d`d`d @######@y@@",
    "@                          @#####@sdsdsd *gd`d```d@######@y@@",
    "@                          @#####@sddds dssg`*`*`d@######@y@@",
    "@                          @#####@ss s*sds*`d`g``d@######@y@@",
    "@                          @#####@sddsssdss`dg``` @######@y@@",
    "@                          @#####@s  ssdd*gd``d``d@######@y@@",
    "@                          @#####@;;;;;;;;;;;;;;;;@######@y@@",
    "@                          @#####@d d ggd*gggg  d @######@y@@",
    "@                          @#####@ gd  *  ggg  dd @######@y@@",
    "@                          @#####@ggdg*g* gggdddd @######@y@@",
    "@                          @#####@gg @ ss gsg   d @######@y@@",
    "@                          @#####@ *@@*ssg`sss`dd @######@y@@",
    "@                          @@@@@@@@ @@@@@g``ss***@@@@@@@@@y@@",
    "@                          @@@@@@@@ ssgg`@``*s* *@@@@@@@@@y@@",
    "@                          @@@@@@@@;;;;;;;;;;;;;;@@@@@@@@@y@@",
    "@                          @@@@@@@@s ``*```gg* @ @@@@@@@@@y@@",
    "@                          @@@@@@@@s`` g` * *g@@@@@@@@@@@@y@@",
    "@                          @@@@@@@@s `` * ** gg* @@@@@@@@@y@@",
    "@                          @@@@@@@@ s* ``***ggg *@@@@@@@@@y@@",
    "@                          @@@@@@@@ s *** ** g **@@@@@@@@@y@@",
    "@                          @@@@@@@@ s` ****ggg*  @@@@@@@@@y@@",
    "@                          @@@@@@@@ss`** gggg    @@@@@@@@@y@@",
    "@                          @@@@@@@@ss`**gggg    *@@@@@@@@@y@@",
    "@                          @@@@@@@@ss````g g***  @@@@@@@@@y@@",
    "@                          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@y@@",
    "@                          @@@@@@@@@  í    í í  @@@@@@@@@@y@@",
    "@                          @@@@@@@@@++++++++++++@@@@@@@@@@y@@",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@y@@",
    "@y  ff  f fffff      ff     ffff    f   @hhh h h hh hh   @y@@",
    "LyCa#####################a#############;@h   h h h  h    @y@@",
    "@e@qqqnddndddndddd nn    hhhhhhhhhhhhhá*Rhhh hhh hh hh  +@y@@",
    "@e@@@ó@@@@@@@@@@@@@@@@@h uuuuuuuuuuuuuu*@  h h h h  h   +@y@@",
    "@e@@@  á á á   á  á  @áhh@@@@@@@@@@@@@C@@hhh h h hh hh  +@y@@",
    "@e@@@Ctttttttttttttt;@yyyyyyyyyyyyyyyyyy@   hhh        ++@y@@",
    "@e@@@@@@@@@@@@@@@á@@g@yyyyiyyyiyyyyyyyyy@   h h  ++++  + @y@@",
    "@e@            @@w@@g@yyyyyyyyyyyyyyyyyy@   hhh     ++++ @y@@",
    "@e@             www@g@yyyyyyyyyyyyyyyyyy@   h        ++  @y@@",
    "@e@ @===@       www@g@yyyyyyyyyyyyyyyyyy@@@@@@@@@@@@@@@@@@y@@",
    "óe@   #         www@g@yyyyyyyyyyyyyyyyyy                  y@@",
    "óe@   #        @w@@@gsyyyyyyyyyyyyyyyyyy11111111111111111C1@@",
    "@C@@0###*>><<**@@@@@tC@@###@###@###@@@@@@dddddddddddddddddd@@"
  ], "TREASURE AREA", "chain",
  [[{"cpx":80,"cpy":80,"initPowerup":"rage","initPowerupLength":3},"Hello world!","I need 5 minutes","15 deaths","and 1 extras","How about you?","===>","Ultimate jump","How to cross it?(Tip:see under the pool :)","Fish head soup :)","3 secs rage activitied"],
    "                                                     ##                                                              @@@@@@@@@@@@@@@@@@@@@@@   >>>>>>>>>       *                                                          @                                                                                @",
    "                                                     ##                                                               @@@@@@@#######@@@@@@@@                   *                                                          @                                                                                @",
    "                                                     ##                                                               @@@@@@@@#######@@@@@@                    *                                                          @                                                                                @",
    "                                                     ##                                                                @@@@@@@#######@@@@@@                  * * *                                                        @              ýýýýýýýýýý                                                        @",
    "                                                     ##                                        ***                     @@@@@@@@##@@@@@@@@@      w             ***                                                         @              ýý#######ý                                                        @",
    "                                                     ##                                          *                     @@@@@@@@@#@@@@@@@@      ww              *                                                          @              ýý#######ý                                                        @",
    "                                                     @@                                        ***                       ##############       www                                                                         @              ýý#######ý                                                        @",
    "                                                     @@                      ****                *                        #############      wwww                                                       wwww              @              ýýý##ý#ý#ý         ssssss                                         @",
    "                                                     @@                        @*              ***                        #############     ww               ***********############                   wwwww              @                                ss    L                                         @",
    "                                                     @@                       @ *                                         ###### #####     ww                 ###   #    ###########                  wwww                @     @                          s     L                                         @",
    "                                                     @@                      @  *                                         ###### ## #     ww                                                         wwww                 @     @                          s     L                                         @",
    "                                                     @@                     @                                             #  ##   #      ww           qnqn                                         wwww                   @     @                          s     L                                         @",
    "                                                     @@                                        *****  ******  **C***              #     ww                                                     wwwwwww                    @     @  ggggCggg&&gg&g&ggggg    s     ==C====                                   @",
    "                                                     @@                                 @C@@@@@                    L     uuuuuuuuuuuuuuwwuh                                                    wwwwwww          @         @     gegggggg              ggCgps           =ýýýýýýi                            @",
    "@@@|@                     @ó@ @@a>>>>####<@@C@   #   @L  R@@                             ##    gg                  L     wwwwwwwwwwwwwwwwuh      nnqn       CBBBBBBBBBBB                       siggw        ``  @;;;;;;;;;@     geg                                               w                        @",
    "L   @                    @@ó@ #              @   #   @L  R @                             ##     g g gggg  gg gggg       wwwuuuuuuuuuuuuuuuh                                           ááííááááá    w            @*********@     gyg                                               w                        @",
    "@yC @                   @@@ó@ #              @   #   @L  R @                             ##    gg                    iiiwwwuuuuuuuuuuuuuuuh     n            < << <<<<<<===========sCssssssssss    w            @*********@     gyg                                               q    w           ááánááná@",
    "@y@                    @@@@ó@ #              @   ##  @L  R @                             ##    g                   **   w`&&a&a@&&@@&&&BBBh  nnn                                                   w            @*********@     gyg                                                    w           á  + ++ @",
    "@y@                   @@@@@ó@ #              @   #   @L  R @                     ^^^^^   ##    gg                 **      @@@@@    @@@@@@@h                                                        w            @*********@     gyg                                                    q   w       áhhhh   @",
    "@y@                  @@@@@@ó@ #              @   #   @L  R @                    g#       ##                      **                                                                                w            @*********@     gyg                                                        w       á   h   @",
    "@y@                 @@@@@@@ó@ #              @       @L  R @                   g## ########         ý ýýýýý ý ýýý                                                                                  w            @*********@     gyg     f                                                  q       á h + h @",
    "@y@                @@@@@@@@ó@ #              @      #@L  R @                   #####            ý                                          `                                                       w            @*********@     gyg    fff                                                  CCC    á  hhh  @",
    "@y@76###ýýý###@@C@@@@@@@@@@ó@##              @       @L  R @                   ###             ýý                                         `                                                                     @*********@     gyg   f f f                                                        á  áh   @",
    "@y@                     @                    @       @L  R @                   ###              ý                                                                                                               @*********@     gyg  f  f  f                                                       áááááááá@",
    "@y@                     @                    @  ww       @ @                   ###              ý                                       `                                                                       @*********@     gyg     f                                                                  @",
    "@y@76###@@@###          @                    @@@ww@@@C@@@@ @ @  @@@  @@ C^^^^&@###              ý                                     +                                                                         @*********@     gyg     f                                                     >>>>         @",
    "@y@                     @                             yyyR                      #                                                  éééí                                                                         @#  # #  #@     gyg@@   f                                                                  @",
    "@y@                     @>>>>>>>>>>>>>>             <<yyyy                      #                                                @@    @                                                                        @                y eR   f                                                                  @",
    "@y@                                    888  888<<<<< Ryyyy                     <#          >>>>>>>>>>>>                          @ffyff@                                                                        @            gggggge@   f         @|                                                       @",
    "@y@                                    @#######@     Ryyyy                    < #                      >>>>>>>>>>>>              @@@y@@@                                                                        @@@ó@@@ó@@Cóó      e@             @                                                        R",
    "@y@                                    @#######@     Ryyyy                   <  #                                  >>>>>>>>>>    @##y##@                      @@@@                                              @@@ó@@@ó@@@óó      e@             @                                                        R",
    "@y@                                    @#######@     Ryyyy                  <   #                                            >   @##y##@                      wwwwR                                                                e@             @ <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< n< n<@",
    "@y@                                    @#######@     Ryyyy                 <    #                                             >                               y  yR                                                          ff  f e@             L                                               á+á      R",
    "@y@@@@@@@@@                            @@@@@@@@@      yyyy                <     #                                              >>@@@@@@@<<<<<<<<<<<<<<<<<<<<<<yyyyR                                             ééééééééééééé@@@@@@@@             @>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ááá      @",
    "@y        R                              @fff@  íééé&<<<<<<<<<<<<<<<<<<<<<      #",
    "@<<<<<<<<y@                              @@@@@                                  #                                                                            @yyyy                                                                                                                                R+á + ++ @",
    "@        y@##  #################          @@@   +                               #               ####                                           #    ###      @<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<####+#++##",
    "@v9*12345&@###############################@@@#####################################################################################################################################################################################################################################################@@@@@@@@@@"
  ],"Adventure trip(fixed again))","chain",
  [[{"cpx":32,"cpy":13},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@+@@@@@@@",
    "@       á                      @",
    "@       á  áááá            á   @",
    "@       á  á   á          á    @",
    "@       á  á    áC      &á     @",
    "@       á  á     á      á      @",
    "@       á  á      á    á       @",
    "@       á  á       áííá        @",
    "@       á  á        íí         @",
    "@       á  á        íí         @",
    "@       á  á        íí         @",
    "@                   íí         @",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@íí@"
  ],"Almost all is invisible", "Ema's Gaming Community",
  // Not approved because is automatic
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@L                              @",
  //   "@Lw                             @",
  //   "@wwfff>>>>>>>>>yyyyy      L     @",
  //   "@ww###         yyyyyyyy   L     @",
  //   "@ww                 yyyyyyy     @",
  //   "@ww         R           L       @",
  //   "@ww       ww            L   RRR @",
  //   "@    <<<  ww            L   RRR @",
  //   "@B&*<   ffww            L  yRRR @",
  //   "@       ##ww             yyyRRR @",
  //   "@         ww             yyyRRR @",
  //   "@                        BBBBBB @",
  //   "@           ffffffffff  ffffffff@",
  //   "@>>>>>>>>BB&##########++########@"
  // ],"Don't move","Ema's Gaming Community",
  [[{},"Lava is comimg","Easy,but everything is reversed","Enter the reverse level ->","water can give you a chance to slow down","Good luck!","===>"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "e                        yyyy@",
    "y11235555555555555555554C@yy@@",
    "y@@yyyyyyyyyyyyyyyyyyyyyyyyyy@",
    "y@@yyyyyyyyyyyyyyyyy@@@yyyyyy@",
    "y@@yyyyyyyyyyyyyyyyyyyyyyyyyy@",
    "y@@yyyyyyyyyyyyy@@@yyyyyyyyyy@",
    "y@@yyyyyyyyyyyyyyyyyyyyyyyyyy@",
    "y@#yyyyyyyyy@@@yyyyyyyyyyyyyy@",
    "y@yyyyyyy@@yyyyyyyyyyyyyyyyyyy",
    "y@yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    "y@y@@wwwwwwyyyyyyyyyyyyyyyyyyy",
    "y@ywwwwwwwCyyyyyyyyyyyyyyyyyyy",
    "y@ywwwyyyyyyyyyyyyyyyyyyyyyyyy",
    "y@yw@@@@@#####################",
    "y@ywwwyyyy@@yyyyyyyyyyyyyyyyyy",
    "y@yyy0yyyyyyy@yyyyyyyyyyyyyyyy",
    "y@yyyyyyyyyyyyy@@yyyyyyyyyyyyy",
    "y@yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    "y@yyyyyyyyyyyyyyyy@@yyyyyyyyy@",
    "y@yyyyyyyyyyyyyywwwyyyyyyyyyy@",
    "y@########yyyyyywyyiyyyyyyyyy@",
    "y@yyyyyyyyyyyyyywyyyyyyyyyyyy@",
    "y@yyyyyyyyyyyyyywyggyyyyyyyyy@",
    "y@yyyyyyyyyyyyyywwwyygggyyyyy@",
    "y@yyyyyyyyy@yyyyyyyyyyyyygggy@",
    "y@yyyyyy**y***y**yyggyyyywwwy@",
    "w@***y*yyyyyyyyyyyywwwwwwwwwy@",
    " @+yyyyyyyyyyyyyyyywwwwwwwCwy@",
    "=@+wwwwwwwwwwwwwwwwwyyyyyyyyy@"
  ],"reverse world","chain",

  // Not approved because this seems based on the default level
  // [[{"cpx":80,"cpy":80},"Glitched and Hacked Level"],
  //   "óóóóóóóóóóóóóóóóó+óó",
  //   "ó              óówóó",
  //   "ó               wwwó",
  //   "ó   ó===ó       wwwó",
  //   "ó     ú         wwwó",
  //   "ó     ú        ówóóó",
  //   "óv^ó0úúú*>><<**óóóóó"
  // ],"Glitched and Hacked Level","Ema's Gaming Community",

  // Seems like a pain to completeand there's not that much skill required
  // [[{}],
  //   "                               ",
  //   "   g    g         g         g  ",
  //   "  g    g         g         g   ",
  //   " g    ggggggggg ggggggggg g    ",
  //   "  g    g         g         g   ",
  //   "   g    g         g         g  ",
  //   "                               ",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "+qqqqqqqqqqqqqw w w   wwwwwwwe@",
  //   "+qqqqqqqqqqqqqw   w w wwwwwwwe@",
  //   "+qqqqqqqqqqqqqw w w    w w w y@",
  //   "+qqqqqqqqqqqqqwwwwwwwwwwwwwwwy@",
  //   "@@@@@@@@@@@ó@@@@@@@@@@@@@@@@Cy@",
  //   "L   qqqqqqqqqqqqqqqqqqqqqqqqqy@",
  //   "L   qqqqqqqqqqqqqqqqqqqqqqqqqy@",
  //   "L   qqqqqqqqqqqqqqqqqqqqqqqqqy@",
  //   "B>>>@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  // ],"stay in wall","chain",

  // Not approved because it's based on the default level
  // [[{"cpx":80,"cpy":80,"initPowerup":"rage"},"Hello world!"],
  //   "óóóóóóóóóóóóóóóóó+óó",
  //   "ó              óówóó",
  //   "ó               wwwó",
  //   "ó   ó===ó       wwwó",
  //   "ó     ú         wwwó",
  //   "ó     ú        ówóóó",
  //   "óv^ó0úúú*>><<**óóóóó"
  // ],"Cheated level and insane fury","Ema's Gaming Community",

  // A bit too easy for the size of the level but tolerable I suppose
  // Removed because it's a copy of "A level... (updated)"
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "                                                     gddd     #     #        @@@",
  //   "                                                     g+dd  #  d  #  d        wwR",
  //   "                                                     ggggggggg=ggggg=ggggCgggyy@",
  //   "                                                     ggggggggggggggggggggggggyy@",
  //   "                                                                            gqq@",
  //   "                                                                            gyy@",
  //   "                                                                            gyy@",
  //   "                                                                            gyy@",
  //   "                                                                            gyy@",
  //   "                                                                            gyy@",
  //   "                                                                            gyy@",
  //   "                        #                                                   gyy@",
  //   "                       ###                                                  gyy@",
  //   "                       ###                                                  gyy@",
  //   "                       ###                                                  gyy@",
  //   "                     ww@@@                                                  gyy@",
  //   "                     ww@@@                                                  gyy@",
  //   "                     ww @                                                   gyy@",
  //   "                     ww @@                                                  gyy@",
  //   "                     ww @@                                                  gyy@",
  //   "                     ww @@@          ó                                      gyy@",
  //   "s                    ww @@@@                                                gyy@",
  //   "syy      m;=f        ww @@@@                                                gyy@",
  //   "sww============      ww @@@@         d                                      gyy@",
  //   "swwwsssssssssss      ww @@@@         d                                      gyy@",
  //   "swwwssssswwwwww      ww @@@@@        d                                      gyy@",
  //   "sswsssssswwBBww      ww óóóóó        d                                      gyy@",
  //   "swwsssssswRwwLw      ww @@@@@        d                                      gyy@",
  //   "swwsssssswwwCww      ww @fff@ggggggggwwwwwww                                gyy@",
  //   "sw&sssssswwwwww      ww @aaa@gggggggg                                       gyy@",
  //   "sw sssssssssssssssssssssssesssss                                            gyy@",
  //   "sw sssssssssssssssssssssssesssss                                            gyy@",
  //   "sw                        esssss                                            gyy@",
  //   "sw                        esssss@@@@@@@@@@@@@                               gyy@",
  //   "sw                         *####@@@@@@@@@@@@@                               gyy@",
  //   "s&***<<<<<<< <<<<<<<<<<<<< *####@@@@@@@@@@@@@                               gyy@",
  //   "gggggggggggg gggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
  //   "gggggggggggg gggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
  //   "gggggggggggg gggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
  //   "gggggggggggg gggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
  //   "gggggggggggg gggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
  //   "gggggggggggg      ffggggg*e*####@@@@@@@@@@@@@                               gyy@",
  //   "@@@@@@@@@@@@@@@@@+@@#####*e*####@@@@@@@@@@@@@                               gyy@",
  //   "@wwwwwwwwwww   @@|@@#####*e*####@@@@@@@@@@@@@                               gyy@",
  //   "@wwwwwwwwwww ;  www@aaaaaae*####@@@@@@@@@@@@@                               gyy@",
  //   "@wwwwwwwwwwwww wwwwwwwwwwwe*####@@@@@@@@@@@@@                               gyy@",
  //   "@wwwwwwwwwwwwwwwwwwCaaaaaa**####@@@@@@@@@@@@@                                yy@",
  //   "@wwwwwwwwwwwwww@w@@@############@@@@@@@@@@@@@yyyy       p                    yy@",
  //   "@wwwwwwwwww;;**@@@@@############@@@@@@@@@@@@@gggg******************************@"
  // ],"Untitled-0","Anonymous",

  // Automatic and impossible to finish. Rejected.
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "                                                  ",
  //   "                                                  ",
  //   "                                                  ",
  //   "@@                          @@                    ",
  //   "@                             R                   ",
  //   "@                             R                   ",
  //   "@ <<<<<<<<<<<<<<<<<<<<<<<<<<  @                   ",
  //   "@                             @                   ",
  //   "@>>>>>>>>>>>>>>>>>>>>>>>>>>>&&@                   ",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  // ],"VERY cOOL LOOP","infinityatom",

  // Too easy
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "                           ",
  //   "                           ",
  //   "                           ",
  //   "                           ",
  //   "                           ",
  //   "                           ",
  //   "                           ",
  //   "                           ",
  //   "                  R@       ",
  //   "                  R@       ",
  //   "         BBBBBB^^^R@       ",
  //   "+@@@@@@@@@@@@@@@@@@@       "
  // ],"vehicla raiders","scratch",

  // A mess (2020-11-15)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "      ippp          ",
  //   "@hhhooopppóóóóóóó+@@",
  //   "@hhhiiiipq  óówóów@@",
  //   "@  ooooppq; ówwwwww@",
  //   "@  oooooqq  ówwwwww@",
  //   "@            y**www@",
  //   "@          dddd@w@@@",
  //   "@v^qqqqqqq@@@*;@@;@@"
  // ],"Untitled","Anonymous",

  // Very nice platforms (2020-11-25)
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuu+@",
    "@u@@@@@@@@@@@@@@@uuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuu@uu@@@uuuuuuu@",
    "@@@@@uuuuuuuuuuu@uuuuuuuuuuuu@",
    "@uuuuuu@@@uuuuuu@uuuuuuu@@@uu@",
    "@uuuuuuuuuuuuuuu@@@@@uuuuuuuu@",
    "@uuuuuuuuuu@@@uuuuuu@uuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuu@@@@uuuuu@",
    "@uuuuuuuuuuuuuu@@@uuuuu@@uuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuu@@@@@@",
    "@uuuuuuuuuuuuuuuuuu@@@uuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuu@@@uuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuu@@@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuu@@@uuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuu@@@uuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuu@@@uuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuu@@@uuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuu@@@uuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@uu@@@uuuuuuuuuuuuuuuuuuuuuuu@",
    "@uuuuuuuuuuuuuuuuuuuuuuuuuuuu@",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  ],"Hell","Ziumbaa",

  // Very nice Rube Goldberg, but it's automatic (2020-11-27 as level-bit)
  // [[{},"@","@","@","@","@","@","@","@","L","ó"],
  //   "@@@@@@@@@Lóóóóóó@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@óó>>>>ó@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@óó@@@@ó@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@óó&@@@@ó@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@Lóóó@@óóóó@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@ó>&@@ó<<<@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@L             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "L  f           óóóóó@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@y&@@*>&@@@@>>>>>>óó@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@y              óR*ó@@@@@   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@ó<<ó<<<<<<<<<<CóóRó@@@@L   +@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@    R         @&y@ @L    ý>@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@  <L   áR    á wy@ @@ >>&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@   #y*uý       wyL    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@&    @         wy@C>>&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@     @        @w@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@>>>&@>>B@*>>&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  // ],"Untitled","Anonymous",

  // Kind of simple, but there's no roof, and I can't get past the lava part (2020-11-29)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@@@@       @@|hh||||",
  //   "@           @yyyyyw+",
  //   "@           @yíyyuww",
  //   "@   @<><><> @yyyyywí",
  //   "@   @@L      yyuyuww",
  //   "@   @@L      yyyíywu",
  //   "@***@@@======vvvvvvv"
  // ],"like","jaxdfrgyhhjujkil",

  // Evil! Unstable blocks are annoying, but I'll take it. (2020-11-29)
  [[{"cpx":80,"cpy":80},"YOUR WELCOME!","can you beat this though?","This next level DO NOT TOUCH THE TOP!!","","","","","","","Do you want to spend some time with the sheeps?"],
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "                              ",
    "@                             ",
    "@                             ",
    "@ @@@@@@@@@@@@@@@@@@@@@@@     ",
    "@ @@@@@@@@@@@@@@@@@@@@@@@     ",
    "@       nnqqqqqnn       R     ",
    "@       nnnnnnnqq       @     ",
    "@&@@@@@@@@@@@@@@@@100CLy@     ",
    "@@@@#################@yy@     ",
    "@@@@#################@yy@     ",
    "@@@@yyyyyyyyyyyyyyyyy@yy@@@ @@",
    "@@@@                 @yy@@hhR@",
    "@@@@                  yy@@hhh@",
    "@L                    yy@@hhh@",
    "@y                    yy@@hhh@",
    "@y   @nnqqnnqnqn    óóyy@@99 @",
    "@y   @           ==   @@@@   @",
    "@y&&v@                hhó@ <<@",
    "@y@@@@>>>>>>>>>>>>>>>>>>ó#+@@@",
    "@y@@@@@@@@@@@@@@@@@@@@@@ów@@@@",
    "@y  qqqqqqqnnnnqqqq       R@@@",
    "@y  nnnnqqnnqqnnnnn       R@@@",
    "@y  qqqnnnnnqqqqqqq       R@@@",
    "@@2@@@@@@@@@@@@@@@@100C==y=@@@",
    "@@@@@@@@@@@@@@@@@@@g@@@LyyyR@@",
    "@@@@@@@@@@@@@@@@@@@@g@@@yyy@@@",
    "@@@@@@gggggggggggggggg@@yyy@@@",
    "@@@@@@@@@@@@@@@@@@@@g@@@yyy@@@",
    "@@@@@@@@||||@@@@@@@g@@@@yyy@@@",
    "#yyyyyyyyyyyyyyy|@@@@@@@yyy@@@",
    "#yyyyyyyyyyyyyyyy|@@@@@@yyy@@@",
    "#yyyyyyyyyyyyyyyyy|@@@hhhhhhh@",
    "#yyyyyyyyyyyyyyyyyy|@@hhhhhhh@",
    "#yyyyyyyyyyyyyyyyyyyy hhhhhhh@",
    "#yyyyyyyyyyyyyyyyyyvv@hhhhhhh@",
    "#yyyyyyyyyyyyyyyyye@@@hhhhhhh@",
    "@@@@@@@@BBBB@@@BBBBB@@^^^^^^^@"
  ],"wdentertainment","A fun little level",

  // Very cool level with evil use of disguise blocks, but unfortunately the end is not reachable (and there's a bug with clipping out of the level if you fall too fast) (2020-11-30)
  // [[{"cpx":80,"cpy":80},"You lost your sheep now you must find him.","Let's see if you can beat THIS!","Pick a side."],
  //   "@@@@@@@@@@@@@@@@@@@@@@@@###@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@wwwwwwwwwwwwwww#wwwwwwwwwwwwwwwwwwwwwwwwwwwwww#úúú@ggggggg@",
  //   "@wwwwwwwwwwwwwww#wwwwwwwwwwwwwwwwwwwwwwwwwwwwww#úúú@ggggggg@",
  //   "@yyCB#######wwww#wwwwww#wwwwwwwwwwwwwww#####www#úúúósssssss@",
  //   "@yy@wwwwwww#wwww####www#www#wwwwwwwwwww#wwwwwww#úúúóggggggg@",
  //   "@yy@wwwwggw#wwww#wwwwww#www#www#########wwwwwww#úúúóggggggg@",
  //   "@yy@wwwwggw#wwww#wwwwww#www#wwwwwwwwwww#wwwwwww#úúúóhvvvvv+@",
  //   "@yy@wwwwwww#wwww#wwwwww#www#wwwwwwwwwww#wwww####úúú@@@@@@@@@",
  //   "@yy@ww######wwww#www####www#wwwwwwwwwww#úúúúúúúúúúú@@      R",
  //   "@yy@wwwwwwwwwwww#wwwwww#www######www####úúúúúúúúúúý@@      R",
  //   "@yy@wwwwwwwwwwww#wwwwww#www#wwwwwwwwwww#úúúúúúúúúý#@@      R",
  //   "@yy@wwwwwwwwwwww#wwwwww#www#wwwwwwwwwww#úúúúúúúúý##@@      R",
  //   "@yy@wwwwwwwwwwww#>>><<<#www#wwwwwwwwwww#úúúúúúúý###@@fffff R",
  //   "@yy@########wwww########www#wwwww#######úúúúúúý####@@vvvvvy@",
  //   "@yy@wwwwwwwwwwwwwwwwwwwwwww#wwwwwwwwwww#úúúúúý#####@@#@#@@y@",
  //   "@yy@wwwwwwwwwwwwwwwwwwwwwww#wwwwwwwwwww#úúúúú######@@@#@@@y@",
  //   "@yy@wwwwwwwwwwwwwwwwwwww&&&#wwwwwwwwwww############@#@@@#@y@",
  //   "@yy@wwwwwwww#######wwww##########wwwwww############@@@@@@@y@",
  //   "@yy@wwwwwwww#wwwwwwwwww#wwwwwwwwwwwwwww############@#@@@#@y@",
  //   "@yyRwwwwwwww#wwwwwwwwww#wwwwwwwwwwwwwww############@#@@@#@y@",
  //   "@yyRwwwwwwww#wwwwwwwwww#wwwwwwwwssswwww############@@###@@y@",
  //   "@yy@@@@@@@@@@BBBBBB@@@@@@@@@@@@@@@@vvvv@@@@@@@@@@@@@@@@@@@y@",
  //   "@yy@@@@@@@@@@@Lyóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóy@",
  //   "@yy@@@@@@@@@@@@y>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>@@",
  //   "@yy@@@@@@@@@@@@y@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@yy@@@@@@@@@@@@yR@@@@@@@@@@@óóóóóóóóóóóR@@@@@@@@@@@@@@@@@@@@",
  //   "@yy@@@@@@@@@@@@yR@@@@@@@@@@@óóóóóóóóóóó@@@@@@@@@@@@@@@@@@@@@",
  //   "@yy@@@@@@@@@@@@y@@@@@@@@@@@@óó@@@@@@@óóóóóóóóóó@@@@@@@@@@@@@",
  //   "@yy@@@@@@@@@@@@yóóóóóóó@@@@@óó@@@@@@@óóóóóóóóóóóóóówwwwwwyR@",
  //   "@yyóóóóóóóóó@@@@@óóóóóóóóóóóóó@@@@@@@&&@@@@@@óóóóóówwwwwwyR@",
  //   "@yyóóóóóóóóóúúóóóóóóóóóóóóóóóó@@@@@@@@@@@@@@@@@@@@@111C@@yy@",
  //   "@@@@@@@@@@@@@@@@@^2^^^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@yyR",
  //   "@@|@@@@@|@@||@@|||||@||||@|||@@@@@@@@@@@@@@@@@@@@@@@@@@@@yyR",
  //   "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwww@@||#####################ýyyR",
  //   "@w wwwww ww  ww     w    w   wwóówwwwwww################ýyy@",
  //   "@w ww ww w ww www www wwww ww wóówwwwwww#####wwwwwwwww##ýyy@",
  //   "@w w w w w    www www    w   wwóówwwwwww#####wwwwwwwww##ýyy@",
  //   "@w  www  w ww www www wwww ww wóówwwwwww#####wwwwwwwww##ýyy@",
  //   "@w wwwww w ww www www    w ww w>&#gCgwww##########wwww##ýyy@",
  //   "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwww@@####www#####wwwwwwwww##ýyy@",
  //   "@w wwwww ww   ww   ww wwww   wwR@####www#####wwwwwwwww##ýyy@",
  //   "@w ww ww w www w ww w wwww ww wR@####www#####wwwww######ýyy@",
  //   "@w w w w w www w   ww wwww ww wR@####wwwwwwwwwwwwwúúúúúúúyy@",
  //   "@w  www  w www w ww w wwww ww wwR####wwwwwwwwwwwwwúúúúúúúyy@",
  //   "@w wwwww ww   ww ww w    w   wwR@####wwwwwwwwwwwwwúúúúúúúyy@",
  //   "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwR@###################ýýýýýýý@",
  //   "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwR@##########################@",
  //   "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwR@##########################@",
  //   "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwR@##########################@",
  //   "@0000000000vvvvvvvvvvvvvvvvvvvv@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  // ],"Water World","wdent",

  // Very simple, but the story is nice (2020-12-05)
  [[{"cpx":80,"cpy":80},"Uh oh! the lava chamber is in your way! try not to die.","Oh noes! someone found you and threw you here! find a way to escape,and don't die!","Thanks for playing! new updates coming soon."],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@@@@@@@@@@@@@@###@@@@@@@@@@@@@@@@  @@@@@@@@@@",
    "@@@@@@@@@@@@@@@#@@@@@@@@@@@@@@@@@  @@@@@@@@@@",
    "@@@ @@@@@@@@@@@#@@@@@       @@@@@  @@@@@@@@@@",
    "@   @@@@@@######@@@@         @@@@  @@@@@@@@@@",
    "@   @@@@@@ @@@@@@@@@ @@@@@@   @@@  @    @@@@@",
    "@   @@            @ e     @@  @@@            ",
    "@                 @ e     @@                 ",
    "@                   e     @@            @@2 +",
    "@1C   C 0 &        Cefffff@@@@@@@@@@@@@@@@@@@"
  ],"Exploration","dagr8estgamer",

  // Seems doable, and the fireball at the end looks cool (2020-12-17)
  [[{"cpx":80,"cpy":175},"PRACTICE OR THIS WILL MAKE YOU RAGE...","Level 1 Ladders and Lava","Heres a small break","Leap of faith?","The Cave of fire draws near...","This is just the start ","In level 2 : i'm a Big Fan","WE IZ SHEEEEEEEEP"," level 2 will be out soon..."],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@#############################################eeeeeeeeeeeee########################                                                    @@@@@@@@@@@@@@@@@@@@",
    "@###################################eeeeeee###eeeeeeeeeeeeee############eeeeeeeeeee                                                    @@@@@@@@@@@@@@@@@@@@",
    "@###################################eeeeeee###ee#########eeee###########eeeeeeeeeee    f   f   f   f   f            f   f   f   f      @@@@@@@@@@@@@@@@@@@@",
    "@###################################ee###ee###ee##########eeee##########ee########@@C5@@@@@@@@@@@@@@@@@@@@@@@@@@@ee@@@@@@@@@@@@@@@@3@@ @@@@@@@@@@@@@@@@@@@@",
    "@###eeeeeeeee#######eeeeeeeeeeee####ee###ee###ee###########eeee#########ee########@@@@@@@@@@@@@@@@@@@@@@@@@@     ee@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@###eeeeeeeee#######eeeeeeeeeeee####ee###ee###ee############eeee########ee########@@@@@@@@@@@@@@@@@@@@@@@@@@     ee@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@###ee#####ee#######ee########ee####ee###ee###ee#############eeee#######ee########@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@###ee#####eeeeeeeeeee########ee####ee###eeeeeee##############eee#######ee########@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@###ee#####eeeeeeeeeee########eeeeeeee###eeeeeee###############eeeeeeeeeee########@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@###ee########################eeeeeeee#########################eeeeeeeeeee########@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@###ee@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@###ee@                                                                          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@###ee@                                                                          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@###ee        f      f      f     f     f     f     f     f     f     f          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@******C********************************************************************1C@ee@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@                                                                              ee@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@        f       f       f       f       f       f       f        f            ee@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@e*C**************************************************************************C**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@e                             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@e                             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@e      f     f     f          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@e    *******************      @@@@@@@@@@@@@@@@@@@@@@@@@@@ff@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@***C**                 *C*    @@@@@@@@@@@@@@@@@@@@@@@@f@f##f@f@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@                              @@@@@@@@@@@@@@@@@@@@@@@##@#==#@##@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@                              @@@@@@@@@@@@@@@@@@@@@@f#===``===#f@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@# #@@@@@@@@@@@@@@@@@@@",
    "@@0@  *  *  *  *  *  *  *  *  *@@@@@@@@@@@@@@@@@@@@@@##=``````=##@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@",
    "@                              @@@@@@@@@@@@@@@@@@@@@@#=````````=#á                                                                     @@@@@@@@@@@@@@@@@@@@",
    "@                              @@@@@@@@@@@@@@@@@@@@@@#=````````=#á                                                                    @@@@@@@@@@@@@@@@@@@@@",
    "@******************************@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C8@@@@@@@@@6@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@4@@@@@@@@@@@@@@@@@@@@@@@"
  ],"Lava and ladders","Mr.Reee",

  // Quite a mess, and I don't think this is possible (2020-12-31)
  // [[{"cpx":80,"cpy":80,"initPowerup":"rage","initPowerupLength":5,"SHEEPurl":"http://cixon.devdrive.org/icon-32.png","SHEEPphys":"dangerous"},"You can do this!","GOOD LUCK."],
  //   "+íí|   á   yyy      í     f   á  há  á         ",
  //   "íí  á      yyy  í   í   u á     á  á    á í ííí",
  //   "í>í   <    <  ííí 0 í íuuf   í á     í    m    ",
  //   "ááí1ííáí0    íí  o í   uuá  á    mí íí^ á  ^ áa",
  //   "   ^         nnn    | íuuuu á  í   qq     í    ",
  //   "     0  áááá nnno      m í    |  i q  í f   á  ",
  //   "  < ^ í     á  | í i  í í íí á  á  íí   á      ",
  //   " 0   í     m     íí  íí      á á  í í    á ííí ",
  //   " í<    í      >>>  í ííí í  0í á>>  f          ",
  //   " < í í^  í              íí a   a    í  íí   á  ",
  //   "  ; í     íí  íí íí |               í          ",
  //   " í    ííí  íí í íí í íí i   >>>í   í      á  á ",
  //   "íí  í   ííí      íí         í  íí í  0; ;      ",
  //   "   í ^íí í   f            á í  í            á  ",
  //   " 0   í           0   0      í í    0    í íí   ",
  //   "   í           ^  á  ááá f  íí   0     íííí  á ",
  //   "  í       íí íííí        á          íí   í   á ",
  //   "    í &&&       í  f     á     á          á á  ",
  //   "                   á         o   p  í  0 0     ",
  //   "00000                               í      á   "
  // ],"EASY","EASY",

  // It's okay, but I think it'd be better if the player weren't lava proof (2020-12-31)
  // [[{"cpx":80,"cpy":80,"initPowerup":"rage","initPowerupLength":15,"SHEEPphys":"solid"}],
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "#                  R++++++++++@",
  //   "#                  R          @",
  //   "#        >>C>>>>@wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######wwRíííííííííí@",
  //   "#          ######wwRíííííííííí@",
  //   "#          ######wwR          @",
  //   "#    ><    ######wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######wwR@@@    @@@@",
  //   "#          ######wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######wwR          @",
  //   "#          ######             @",
  //   "#          ######             @",
  //   "##@##############@@@@@@@@@@@@@@"
  // ],"Untitled","DifficultGuy1928",

  // Interesting concept, but too similar to default level, and rage effect is pretty annoying in general (2021-01-01)
  // [[{"cpx":80,"cpy":80,"initPowerup":"rage","initPowerupLength":3},"Hello world!"],
  //   "@@@@@@@@@@@@@@@@@+@@",
  //   "@íííííííííííííí@@é@@",
  //   "@ííííííííííRíííRííí@",
  //   "@ííí@===@ííRíííéííí@",
  //   "@íííííéííííRíííRííí@",
  //   "@íííííéíííííííí@@@@@",
  //   "@v^@0ééé>>><<<*@@@@@"
  // ],"TimelimitedGame","DifficultGuy1928",

  // Interesting level, but the rage powerup is annoying
  // [[{"cpx":80,"cpy":80,"initPowerup":"rage"},"Hello world!"],
  //   "@+@@@@@@@@@@@@@@@@",
  //   "+u@yyyyyy@@@@yyyu@",
  //   "@u@@@@@@yyyyyy@@u@",
  //   "@uuóóóóóó@y@@@ó@u@",
  //   "@@@@@@@@@@y@óóó@u@",
  //   "@óóuuyy@yyy@ó@@@u@",
  //   "@ó@@@@yyy@@óóóó@u@",
  //   "@óóóóy@@@ó@ó@@@@u@",
  //   "@@@@@yóóóóóóóów@u@",
  //   "@@y  y@@@@@@@@w@u@",
  //   "@óy@ @@yyyyyyyw@u@",
  //   "@ó@ó @óó@@@@@ó@@u@",
  //   "@@yó@óó@yyyyuuó@u@",
  //   "@@y@yó@yó@@@@@@@u@",
  //   "@@y@y@yó@óóóyy@@u@",
  //   "@@yyy@y@óó@@@y@@u@",
  //   "@óó@@@y@ó@yyyy@@u@",
  //   "@@@yyyy@ó@y@@@@@u@",
  //   "@y@y@@yuó@yóóóR@u@",
  //   "@yyyyy@@@@@@@ó@@u@",
  //   "@@y@y@uuóóóóóó@@u@",
  //   "@@y@@@uu>>>>>B@@u@",
  //   "@íRíónnnnóíLíí@@u@",
  //   "@íRíónnnnóíLíí@@u@",
  //   "@íRíóóóóóóíLíí@@u@",
  //   "@íRííííííííLí>@@u@",
  //   "@ííííííííííííR@@u@",
  //   "@í<<<<é<CBéééé@@u@",
  //   "@ííííííííLíííí@@u@",
  //   "@í<<<<<<<é@íí>@@u@",
  //   "LííííííííííííR@@u@",
  //   "LB<<<<íííííííí@@u@",
  //   "Lííííííííííííí@@u@",
  //   "Lííííííííííííí@@u@",
  //   "@<<<<<<&>>>>>>@@u@",
  //   "@@@@@@@@@@@@@@@@C@"
  // ],"TheHardestLevel!","DifficultGuy1928",

  // Doable (2021-01-07)
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@",
    "Lwwwwwwwwwwwwwwwwwwó",
    "@w>>>>>>>>>>>>>>>LwR",
    "éw@wwwwwwwwwwwwwwRwR",
    "@w@w<<<<<<<<<<<<wLwR",
    "@w@w@wwwwwwwwwwRwLwR",
    "@w@w@w<<<<<<<<w@wLwR",
    "@w@w@w@wwwwww@w@wLwR",
    "@w@w@w@w<<<<w@w@wLwR",
    "@w@w@w@wR+@@w@w@wLwR",
    "@w@w@w@wRwwww@w@wLwR",
    "@w@w@w@wR>>>&@w@wLwR",
    "@w@w@w@wwwwwwww@wLwR",
    "@w@w@w@>>>>>>>&@wLwR",
    "@wwwRwwwwwwwwwwwwLwR",
    "@&<<é>>>>>>>>>>>&ww@",
    "é          Róóóé@wé@",
    "é          RóóóówwwR",
    "éóóóBBBBBóóRóóóówwwR",
    "é   óóéóó      ówwwR",
    "é   óóéóó      <<<<@",
    "@>>>>>é<<<B@<<<@@@@@"
  ],"UltraDifficult Level","DifficultGuy1928",

  // Too easy (2021-01-13)
  // [[{"cpx":80,"cpy":80},"Welkom in mijn wereld!"],
  //   "                    ",
  //   "                    ",
  //   "                    ",
  //   "                  +@",
  //   "                    ",
  //   "    @ C @  *  @  @  ",
  //   "0@@#################"
  // ],"Noob Level","nobody",

  // Too easy (2021-01-17)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@@@@@@@@@@@@@@@@@@@@",
  //   "@                  @",
  //   "@                  @",
  //   "@                  @",
  //   "@                  @",
  //   "@                 +@",
  //   "@@@@@@@@@@@@@@@@@@@@"
  // ],"SIMPLE","-Witherman_",

  // Too easy (2021-01-17, as a level-bit)
  // [[{},"@","@","@","@","@","@","@","@","@","@"],
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@                                              ",
  //   "@                                         ",
  //   "@                                    ",
  //   "@                  ",
  //   "@                     @@@       ",
  //   "@                              ",
  //   "@              B@@@      +",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  // ],"Untitled","Anonymous",

  // Too empty/plain/simple (2021-01-24)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@                       e                        ",
  //   "@                       eooooo                   ",
  //   "@                       eooooo         @@@       ",
  //   "@                       eooooo         @@@       ",
  //   "@                       eooooo         @@@       ",
  //   "@                       eooooo         @@@       ",
  //   "@          ffff  ##     eooooo        B@@@      +",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  // ],"Untitled","Anonymous",

  // Passable I guess; I like the ending (2021-01-26)
  [[{"cpx":80,"cpy":80,"initPowerupLength":999},"GOOD JOB! :D","YOOOOOOOOOOOOUUUUUUUUUUUUUUUUUUUUUUUU WIIIIIIIIIIINNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@        ##a###ggfg#ggggg@@@@||@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@        ######ggegeggggg@+ á  óóóóóó+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@               ge#e#####@@9C  óóóóóó+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@                        óóóó  @Lóóóó+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@   #@@&@@@@a@@@@@@0@@@L   óó  @Lóóóó+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@   #@@@@@@@a@@@@@@@@@@@>>>>>^^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@v^ #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  ],"idk","something",

  // Too easy (2021-01-27)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@@@@@@@@@@@@@@@@@+@@",
  //   "@Lwwwwwwwó ###    í@",
  //   "@Lwwwwwwwó        í@",
  //   "@Lwwwwwwwó        í@",
  //   "@Lwwwwwwwó        í@",
  //   "@Lwwwwwwwó        í@",
  //   "@@&&&&&&&vv^^^vv^^^@"
  // ],"1","I Am A Loser",

  // Okay I guess (2021-02-06)
  [[{"cpx":80,"cpy":80,"initPowerup":"slam"},"GOTCHA SUCKER"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@        ",
    "@íí                          áá@        ",
    "@íí                          áá@        ",
    "@í                           áá@        ",
    "@í@                          áá@        ",
    "@e@óCo<<<<<<<<<<<<<@         áá@        ",
    "@e@ó@              @ó        áá@        ",
    "@e@ó@               óó@@@@@@0á@@        ",
    "@e                  @óóóóóóóó ó@        ",
    "@ @@@@@@@@###@###CC @óóóóóóóó ó@        ",
    "@gggggggggggggggggg @@@@@@@@@ @@@@@@@@@@",
    "g                   @@@@wwww +a@@@@@@@@@",
    "@ggggggggggggggggggggg@@wwwwwBB@@@@@@@@@"
  ],"IF U MAKE IT PAST THIS LEVEL, YOU HAVE MY RESPECT","Rebelthunder956",

  // Automatic (2021-02-20)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@||                @",
  //   "@                  R",
  //   "@                  R",
  //   "L  <<<<<<<<<<<<<<  R",
  //   "L                  @",
  //   "L                  @",
  //   "@>>>>>>>>>>>>>>>>&&@"
  // ],"very good screen saver (not)","Anonymous",

  // Not possible to complete (2021-02-25)
  // [[{"cpx":80,"cpy":80,"SHEEPurl":"https://charlie-moomoo.github.io/cowcircle.png"},"3","2","1","GO!"],
  //   "         @@@@@        @@@@@       @@    ",
  //   "              @      @     @     @ @    ",
  //   "              @           @        @    ",
  //   "         @@@@@           @         @    ",
  //   "              @        @@          @    ",
  //   "              @       @            @    ",
  //   "         @@@@@       @@@@@@@     @@@@@  ",
  //   "                                        ",
  //   "                                        ",
  //   ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
  // ],"321","Charlie",

  // Good enough, but right side of level isn't necessary (or faux endpoints should be properly blocked off) (2021-03-16, as a level-bit)
  [[{},"@","@","@","@","@","@","@","@","@","@"],
    "@@@@@@@@@@@@@@@@@@@@@@@@e         +    +  óóó@@@@@@         ",
    "@@@@@@@@@@@@@@@@@@@@@@@@e              <^         R         ",
    "@@@@@@@@@@@@@@@@@@@@@@@@e               <óóó<<<<< @         ",
    "@@@@@@@@@@@@@@@@@@@@++@@e====                     @         ",
    "@@@@@@@@@@@@@@@@@@@@  @@e=====                 e>&@         ",
    "@@@@@@@@@@@@@@@@@@@@    e======                e@@@         ",
    "@@@@@@@@@@@@@@@@@nL     e=======              e@@@@         ",
    "@        n@@@@@@nnn     =========            e@@@@@         ",
    "@          @@@@nnn  vvC**=========          e@@@@@@         ",
    "@           @@@n    @@@@@==========        e@@@@@@@         ",
    "@   C^#^           &@@@@@==========       e@@@@@@@@         ",
    "@     ó f         @ @@@@@==========      e@@@@@@@@@         ",
    "@   f ó L       ^f##@@@@@==========wwwww@@@@@@@@@@@         ",
    "@v^^^ýýý@>><<fCf####@@@@@==========@@@@@@@@@@@@@@@@         "
  ],"Untitled","Anonymous",

  // This is a modification of flappyball (2021-03-24)
  // [[{"cpx":80,"cpy":80,"SHEEPurl":"1200px-McDonald's_Golden_Arches.svg"},"flappyball","1","2","3","4","finish"],
  //   "                  #     #              +@",
  //   "                  #     #              +@",
  //   "                  #     #              +@",
  //   "                  #         #          +@",
  //   "                            #          +@",
  //   " @                          #          +@",
  //   "+@      @                   #           @",
  //   "+@     @@@              #   #           @",
  //   "+@    @@@@@       #     #  ^#           @",
  //   "+@   @@@@@@@     @@ 1 @@ 2@@ C3gg       @",
  //   "+@  @@@@@@@@@  @@#@hhCh            gg5 &@",
  //   "+@@@@@@@@@@@@@C###@###################gg@"
  // ],"Untitled","Anonymous",

  // Nice simple level; I manually shortened the level to remove the excess air (2021-03-24)
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "                                                                                                                                                                   ",
    "                                                                                            @@@i                                                                   ",
    "                                                                                        @@@                                                                        ",
    "                                                                                                                                                 @@@               ",
    "                                                                                                                                                   +@              ",
    "                                                                                     @@@                                                           +@@@@@@@        ",
    "                                                                                                                 e  wwwwwwwwwwwwwwwwwwwwwwwwwwwww         @      0 ",
    "                w@@@   @@@                            @@@                                                        e e>>>>>>>>>>>>>>>>>>>>>>>>>>>>>@@@      @        ",
    "                w              @@@w                                              @@@                          e @@ e                               @   @  @    h   ",
    "                w                 w       @@@                    @@@                                   @@@    e                                    @   @  @        ",
    "          @@@   w          @@@@   w               @@@        @@@             @@@                            e                                      @   @           ",
    "@@@             w                 w   @@@                            @@@                            C @     e                                      @wwwwwwá        ",
    "@    @@@        w                 ww          @@@         @@@             C                         @@@                                            @wwwwwwá        ",
    "@  @          C w                 #wC                                    @@@                                             f                         @@@@@@@@        ",
    "@@@@ffffffffff@@@fffffffffffffffff@@@@ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff                fffffffffffffffffffffffff"
  ],"12345","wyatt",

  // Cool level but not possible to complete (2021-03-24)
  // [[{"cpx":80,"cpy":80},"Yay You Did It!","Or Did You","====>"],
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                    @                                  ",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@yyyyy@@@@@@ó                                    @                                  ",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@yyyyy@@@@@óó                                    @                                  ",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@yyyyy@@|@óóó                                    @                                  ",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@wwwww@L                                         @                                  ",
  //   "@@@@@@@@@@@@@@@@@@@@e        @                          es        @yyyyy@@ C>>>                                    @                                  ",
  //   "@@@@@@@@@@@@@@@@www@e@@@@@@@ @       @C@@@@@i     ``````es        @wwwww@@ @@@@                          í         @                                  ",
  //   "@@@@@@@@@@@@@@@@wwwáe&   LR@ @       @@@@@@@@     ``````eseCýý##úú@yyyyy@@ @@@@                 e012222222@@^^^^^^^@                                  ",
  //   "@@@@@@@@@@@@@@@@wwwáe&   B|@ @                         #ese@      @wwwww   @@@@                 e@@@                                                  ",
  //   "@@@@@@@@@@@@@@@@wwwáe      @ @                         #ese@      @yyyyy@@B@@@@                 ee@@                                                  ",
  //   "@@@@@@@@@@@@@@@@www@vvvvv@ @ @                         #ese@      @yyyyy@@@@@@@                 ee@@                                                  ",
  //   "@@@@@@@@@@@@@@@@www@@@@@@@ @ @ C##^ss###################ese@      @yyyyy@@@@@@@                 @@@@                                                  ",
  //   "@@@@@@@@@@@@@@@@www@@@@@@@ @ @ @##sss####@              ese@      @yyyyy@@@@@@@                    @                                                  ",
  //   "@@@@@@@@@@@@@@@@www@@@@@@@ @ @ @##sss####@              ese@      yyyyyy@@@@@@@                    @                                                  ",
  //   "@@@@@@@@@@@@@@@@www@@@@@@@ @ @ @##sss####@ ssssssssssssssse@      yyyyyy@@@@@@@                    @                                                  ",
  //   "@              @www@@@@@@@ @ @ @##sss####@ yyyyyyyyé wwwwwe@      yyyyyy@@@@@@@                    @                                                  ",
  //   "@               www@@@@@@@ @ @ @sssss####@                 @      yyyyyy@@@@@@@                    @                                                  ",
  //   "@               www@@@@@@@ @ @ @ss########@@######@@@######@@@@@@@@yyyyy@@@@@@@                    @                                                  ",
  //   "@               wwwó       L   @ss                         @@@@@@@@yyyyy@@@@@@@                    @                                                  ",
  //   "@              @www@@@@@@@^@á@psss                         @@@@@@@@yyyyy@@@@@@@                    @                                                  ",
  //   "@@@@@@@@@@@@@@@@&&&@@@@@@@@@+@ssss                         @@@@@@@@yyyyy@@@@@@@fffffffffffffffff ff@                                                  "
  // ],"Untitled","Anonymous",

  // Too easy (2021-03-25, submitted as level bit)
  // [[{},"@","@","@","@","@","@","@","@","@","@"],
  //   "@@@@@@@@@@@@@@@@@@@@@@@@+@@@@@@@",
  //   "@       á                      @",
  //   "@       á  @@@@@           á   @",
  //   "@       á  @   @@         á    @",
  //   "@       á  @    @C      &á     @",
  //   "@       á  @     á      á      @",
  //   "@+++++  +  @      á    á       @",
  //   "@+++++  @  @       á@@á        @",
  //   "@+++++  @  @        íí         @",
  //   "@+++++  @  @        íí         @",
  //   "@+++++  @  @        íí         @",
  //   "@+++++              íí         @",
  //   "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@íí@"
  // ],"Untitled","Anonymous",

  // Okay use of rage; fairly simple though, but passable (2021-04-09)
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@                                +@",
    "@                           @@@@@@@",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@             @@@                 @",
    "@        @@@C;@i@                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@                                 @",
    "@@@@@o@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  ],"Rage Bounce","AwayFromKeyword",

  // Too similar to default (2021-04-15)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@@@@@@@@@@@@@@@@@+@@",
  //   "@              @@ @@",
  //   "@                 @@",
  //   "@   @@@@@         @@",
  //   "@     @           @@",
  //   "@     @C       @@@@@",
  //   "@@@@@@@@@@@@@@@@@@@@"
  // ],"My first level","Blake",

  // Very cool automatic level; will have an exception for this (2021-04-16)
  [[{"cpx":80,"cpy":80},"Hello!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "Ly             hhh     R        R",
    "@y>>>>         hhh              R",
    "@yyy       +   hhh <<<          R",
    "@yyy        á  hhh              R",
    "@yyy      R    hhh    &<<<     y@",
    "@yyy       &&<<hhh          áááy@",
    "@yyy           hhh          yyyy@",
    "@              hhh          yyyy@",
    "@  B<<         hhh  >>>>úúú@yyyy@",
    "@C             hhh     @úúúóyyyy@",
    "@>>>>>>&h>>>>>>>&@@@@@@@>>>>&@@@@"
  ],"Mario Maker Auto Level","Random Person 2.2",

  // Good level (2021-04-16)
  [[{"cpy":50},"WELCOME","Wow, you made it","BUT NOT ENOUGH","...","HOW","how did you do it...","how did \"YOU WIN\"","LOL","YOU R LOOKING","SECRETS LOL"],
    "@@@@@@@@@@@<<<<<<<<<@@@*#@@@#######@@@@@@@",
    "@wwwwwwwwww@@@@@@@@@@@@*   @wwwwwwwwwwwww@",
    "@ww@@@     @@@@@@@@@@@@* @ @w000000@wwwww@",
    "@ww@       <<<<<<<<<@@@* @ L       @yyyyy@",
    "@ww@    @  óóóóóóóóó@@@* @ L       @yyyyy@",
    "@ww@       óóóóóóóóó@@@* @ L       @yyyyy@",
    "@   @      <<<<<<<<<@@@* @ L       @yyyyy@",
    "@gg @  @   @@@@@@@@@@@@* @ L       @yyyyy@",
    "@   @      @@uuuuuuuu@@* @ L       @yyyyy@",
    "@ 33@                 y* @ L       @yyyyy@",
    "@   @      @C222211111y* @ L       @yyyyy@",
    "@44 @íííííííííííí@@@@@y* @ L       @yyyyy@",
    "@   @            @@@@@y* @ L       @yyyyy@",
    "@ 55@            @@@@@y* @ L       @yyyyy@",
    "@   @            L  óóy* @ L       @yyyyy@",
    "@66 gggggggggggggL  óóy* @ L       @yyyyy@",
    "@úúúúúúúúúúúúúúú+L  óóy* @ L       @yyyyy@",
    "@úúúúúúúúúúúúúúú+L  óóy* @ L###### @yyyyy@",
    "@ggggggggggggggggL  óóyy @         @yyyyy@",
    "@@@@@@@@@@@@@@@@@@>>>>@@@@@@@@@@@@@@yyyyy@",
    "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwóyyyyy@",
    "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwóyyyyy@",
    "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwóyyyyy@",
    "@wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwóyyyyy@",
    "@@ááááááááááááááááááááááááááááááááá@@@@@@@"
  ],"oof","A MAN DUDE PERSON",

  // Level is okay... (2021-04-25)
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                       +             ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                                     ",
    "                                       @@            ",
    "                         #            @  @           ",
    "íí@                           @@    @@    @qq qqqd  +",
    "íí@                   #     #  @@^^^@  q  @qqqq qq  +",
    "íí@                                    q@@@qqqqdqq d+",
    "íí@                                     ddqqdddqqqd +",
    "íóó                     @#@            qdqqqdqdq qqq+",
    "íó   @@@@              @ááá@           qdqdqqdqq qdq+",
    "í@  @    @            @ááááá@          qdq qqdqdqqdq+",
    "í@ @      ó@@@@@@@@@@@@áááááá@         @@qqqd ddqqdq+",
    "+@@@                  áá+++áá@@C@@@@@@@@qqqddqqdqqdq+"
  ],"can you go through it?","techadonssss",

  // Not possible to complete (2021-04-28)
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "                    ",
  //   "                    ",
  //   "                    ",
  //   "       a            ",
  //   "      @@###         ",
  //   "      @@            ",
  //   "^vvv=#@             "
  // ],"LOL","A",

  // Very good level, and a very good introduction to the different blocks in Platformre :D (2021-05-03)
  [[{"cpx":80,"cpy":80,"SHEEPurl":"https://imgpile.com/images/7p5ChX.png"},"Made by JerBeaRocks","Use this powerup by pressing space, then you can jump high and go through fire.","Good job! You made it past my trap! The next  checkpoint is totally real! =)","Touch this to reverse gravity!","I wonder what the X means?","LOL","The end! Thanks for playing!","Here is the real end! =)"],
    "á                                                                                                                                wwwww##www##www##www##wwwwwwwwwwwwwwwww    ###################                                        #################################íííííííííííííííííí                                                                                                                                        e                      á      ",
    "á    ááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááááá  e                                wwwww##www##www##www##wwwwwwwwwwwwwwwww    yyyyyyyyyyyyyyyyyyy                                        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                                                                                                                          e                      á      ",
    "ááá                                                          íá                                 e@@@C@@aa                        wwwww##www##www##wwwwwwwwwwwwwwwwwwwwww    yyyyyyyyyyyyyyyyyyy                                        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                                                                                                                          e                      á      ",
    "  ááá                                                        íá                                 e                                wwwww##www##www##wwwwwwwwwwwgóógwwwwwww   e@@@@yy@@@@@yy@@@@@@                                        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                                                                                                                          e                      á      ",
    "    ááá                                                      íá                                 e                                wwwww##www##www##www##wwwwwwge gwwwwwww   eyyyyyyyyyyyyyyyyyyy                                        yygggggggggggggyyyyyyyyyyyyyyyyyy                                                                                                                                                          e                      á      ",
    "      ááá                                                    íá                                 e                                wwwww##www##www##www##wwwwwgge gggggwww   eyyyyyyyyyyyyyyyyyyy                                        yyyyy yyyyyyyyyygyyyyyyyyyyyyyyyy                                                                                                                 á                                        e                      á      ",
    "        ááá                                                  íá                                 e                                wwwwwwwwww##www##www##wwwwgg e yyyyggww   eyyyyyyyyyyyyyyyyyyy       qqqqqqqqqqqqqqqqqq               yyyyyCyyyyyyyyyyyygyyyyyyyyyyyyyy                                                                                                                g+g                                       e                      á      ",
    "          ááá                     L@@@||||                   íá                                 e                                wwwwwwwwww##www##www##wwwwg  e yyyyysww   eyyyyyyyyyyyyyyyyyyy       qqqqqqqqqqqqqqqqqq   á           yyyyyyyyyyyyyyyyyyyygyyyyyyyyyyyy                                                                                                               ggggg                                      e                      á      ",
    "            ááá                   L                   á      íá                                 e                                wwwww##www##www##www##wwwwg  e    yysww   eyyyyyyyyyyyyyyyyyyy*******nnnnnnnnnnnnnnnnnn**h*55**       yyyyyyyyyyyyyyyyyyyyyygggygggyggg                  óóó                                                                                         ggggggg                                     e                      á      ",
    "              áááá                L   ffff   @    @@@h@éééééééá                                 e                                wwwww##www##wwwwwwww##wwwwg  e    yysww   e                          qqqqqqqqqqqqqqqqqq               yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy              óóó                                                          @@@óó@@@é@@@óóó@@@@éééé@@@@@66@@@@ggggggggg@@@@@@@@@@@@@@@@@55>>>              e                      á      ",
    "               ###óóó@@@C@@   R0óóL   ====@C@@ffff@ á ááááááá@@                                 e                                wwwww##www##wwwwwwww##wwwwgg e  C33ggww   e                                                           yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@@@@C@44@ óóó                                                                                                                              L              e                    gdg      ",
    "@@||||||||||||||              R@ww    @@@@@@@@@@@@@ á         óó                                e                                wwwww##wwwwwwww##www##wwwwwgggggggggwww   e                                                           yyyyyyyyyyyyyyyyyyyyyyyyyByyyByyy                                                                                                                                           @>>>           e                   ggdgg     ",
    "@@                            R@     @@             á  áááááááá@@                               e                                wwwww##wwwwwwww##www##wwwwwwwwwwwwwwwww   e                                                           yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                                                                                                              L           e                  ggqdqgg    ",
    "@Lwwwwwwwwwwwwww              R@     @              á áá        @@                              e                                wwwww##www##www##www##wwwwwwwwwwwwwwwww   e                                                           yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                                                                                                              @>>>&&      e                 ggqndnqgg   ",
    "@@00ffffffffffff&<L           R@     @              á á          @22@hó                                                          wwwww##www##www##www##wwwwwwwwwwwwwwwww   e                                                           yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyýýýýýýýýýýýýýýýýýýýýý##ýýýýýýúýýýý####ýýýýúúúýýýý#ýýýúýýýý####ýýýýúúýýC&&     ff   f   fff    ffff                                                        e                ggqnqdqnqgg  ",
    "@@BBBBBBBBBBBBBB   *****B##BpvR@11ooo@              ááá              C@@@@@@@@@pppaa&############################################wwwww##www##www##www##wwwwwwwwwwwwwwwww@@@@@####################################################ííí&&&&&&yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=====================vv======v====vvvv====vvv====v===v====vvvv====vv=====###########################                                                      egg7777g0000gg&&ggqnqn+nqnqgg "
  ],"Many Block Types","JerBearRocks",
];
var loc=window.location.pathname.slice(window.location.pathname.lastIndexOf('/',window.location.pathname.lastIndexOf('/')-1),window.location.pathname.lastIndexOf('/'));
if (loc=="/platformre"||loc=="/maker") {
  var vroom="";
  for (var i=0;i<exampleLevels.length;i+=3) {
    vroom+='<li onclick="example('+(i/3)+');">'+exampleLevels[i+1]+' by '+exampleLevels[i+2]+'</li>';
  }
  document.querySelector("#EXAMPLES").innerHTML+=vroom;
}
try {
  if (!SHEEP.dismissed.platformreexplore) {
    SHEEP.dismiss('platformreexplore');
    SHEEP.notify('You can now play other people\'s levels!','/platformre/explore');
  }
} catch (e) {console.log(e);}
/* MADE BY SEAN */
