var exampleLevels=[
  [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@       @",
    "@@@@@@@@@@@@@@@@@@@        eeeeeeee@@@      +@",
    "@@@@@@@@@@@@@@@@@@@        effffffe@@@      @@",
    "@@@@@@@@@@@@@@@@@@@        @@@@@@@e@@@      @@",
    "@#########@@@L             @@@@@L  R@@      @@",
    "@###eeee##@@@@>eee<vw      @@@@@L  R@@      @@",
    "@##e    ee@@@@#eeeR@w     p@@@@@L  R@@      @@",
    "@#e       @@@@Leee#@w      @@@@@L  R@@      @@",
    "@e  f^@ww#@@@@#eeeR@w      @@@@@L  R@@      @@",
    "@   #@@&ww@@@@L   R@w      @@@@@L  R@@      @@",
    "@   #@@ww#@@@@L    Raw# # #@@@@@L  R@@      @@",
    "@    @@&ww@@@@L&  R@ww# # #@@@@@L  R@@      @@",
    "@^   @@www@@@@L    Rww# # #@@@@@L  R@@      @@",
    "@#   @@w&w@@@@L   R@ww# # #@@@@@L  R@@      @@",
    "@    @@##w@@@@L  &@@ww# # #@@@@@L  R@@      @@",
    "@   ^@@www@@@@L   R@ww# # #@@@@@L  R@@      @@",
    "@   #@@www@@@@L    Rww# # #@@@@@L  R@@      @@",
    "@    @@w&w@@@@L&  R@ww# # #@@@@@L  R@@      @@",
    "@    @@w##@@@@L    Rww# # #@@@@@L  R@@      @@",
    "@^   @wwww@@@@L   R@ww# # #@@@@@L  R@@      @@",
    "@#   @ww##@@@@L  &@@ww# # #@@@@@L  R@@      @@",
    "@    #    @####   R@ww# # #@       R@@      @@",
    "@    #   #L       #@ww# # #@aaaa<  R## Ciiii@@",
    "@    #            #@a@#p#p#@@@@@@      #@@@@@@",
    "@v^^^@Cv*<><>*v^BB@@@@@@@@@@@@@@@@@>####@@@@@@"
  ],"Untitled-0"," Steven",
  [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@**              @        @ ####@",
    "@**              @      @;@+####@",
    "@**  @@@@@@@@@@;;       @@ +    @",
    "@**           @@@@ii@@@ @@ +aaa @",
    "@**           @@@   @@@ @@  ### @",
    "@**p@@>>>@m   @@@  t@@@ @@  ### @",
    "@**@@@@@@@@   @@@  @@@@p@@      @",
    "@  ########   @@@  @        ### @",
    "@  ########   *ww  @        ### @",
    "@             *ww  @        ### @",
    "@@@aa######@pp@@@ii@oo@@@@@@@@@p@"
  ],"Untitled-0"," Zach",
  [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@   *******    ss  #### wwww@    @g    @",
    "@   wwwwwww        #### @@@w@ @;;@g    @",
    "@   w#####w           # @+@w@ @***g    @",
    "@   wwwwwww    vv     # @+@w@ @***g    @",
    "@   ww####w    ##       @ @w@ @***g    @",
    "@   wwwwwww    ##       @ @ww @***g    @",
    "@   w#####w    ##       @ @@@i@***g    @",
    "@   wwwwwww    ##       @ ********g    @",
    "@ >>*******^^^^##ggg&ggp@         g    @",
    "@@@@@@@@@@@@@@@@@@@@@@@@@p@@@@@@@@@@@@@@"
  ],"Untitled-1"," Zach",
  [[{}],
    "ááááááááááááááá+á",
    "áááááááááááááááíá",
    "á      L   L   yá",
    "á      L >   **tá",
    "á      óy>>>&   á",
    "á  Lúóóóyý      á",
    "L    >>>        á",
    "áa>>Báááááááááááá"
  ],"Recursive Death"," Sean",
  [[{}],
    "@@@@@",
    "Ly  g",
    "ýy>;ý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "ýyágý",
    "@yágý",
    "@ ágý",
    "@&á+@"
  ],"Slammer"," Sean",
    [[{}],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "+ááááááá      u u u   uuuuuuuu@",
    "+ááááááá      u   u u uuuuuuuu@",
    "+             u u u    u u u u@",
    "+íí  í í @úúú@uuuuuuuuuuuuuuuu@",
    "@@@@@@@@@@@ó@@@@@@@@@@@@@@@@@ @",
    "L    L    á á               q @",
    "L  L L L                    q @",
    "L  L   L á á á                @",
    "BBBB>>B@@@@@@@@@@@@@@@>>>#a#<@@"
  ],"Untitled-0"," ANONYMOUS",
  [[{}],
    "************",
    "*yyyyyyyy*+*",
    "*yyyiyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "*yyyyyyyy*y*",
    "********p***"
  ],"Teh Bleu Levle"," Sean",
  [[{},"Welcome to the factory"],
    "`||||||||`",
    "LR||LLRee+",
    "LeeR||ReRR",
    "LBeee|eeeR",
    "LReLeeeReR",
    "LeeeLReBeR",
    "LeReeeBeeR",
    "LeBR|eeeRR",
    "LeRLBRLeeR",
    "`0BBBBBBB`"
  ],"Factoyr"," Sean",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@############################",
    "@w   w    +@     íqyqq    ###",
    "@  w   ww@@@ í    qyqq     ##",
    "@ @@@@m@@         qqqq     *#",
    "@  w w            qqqq      #",
    "@^       @ @   == qqyq      #",
    "@      @@###@@    qqyq  C*  #",
    "@##* @@||#||#|ééé**@@@&&@   #",
    "@@@@@ywyywwwwwuuuuuuíuuu@  *#",
    "@ @# ywwwwyyyyuuíuuuuuuu@*  #",
    "@ @# yyyyyywwwuuuuuuuuuuL   #",
    "@    wwwwwwwyyuuuuuuuuuu    #",
    "@C***&&&&&&&&&@@@@@@@@@@@@&&@"
  ],"a level - remake"," Anonymous",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@óóóóyyyyyy@@@@@@@@@@óóó@@@@@@@@",
    "@                   íí  úúúuuwwu@",
    "@ C@@@@@ó@@@<@<@<ó     úúuuuwwu+@",
    "@                í@  úúúuuwww@@@@",
    "@    f@@ó@ó@f     @@@@qnnníííííí@",
    "@&@@@@íííííí@@@   @www    í     @",
    "ó    qqnqqnqqn    @wíw          @",
    "@   qnnqnnqnn    óáwíw    vv vve@",
    "@ @@@@@@@@@@<@<@@ áwíw   íí ## e@",
    "@ yuyuyuyuy       áwíw   í  ## e@",
    "@||||@@@yuy       qwíw      ##  @",
    "L      íéééC@@@@@@@*í***>>>>@@  @",
    "L   R uuuuuíuuuuuuyyíywwwwyywwC R",
    "L  R#íuuuuíuuuuuyyyywwyyyywwyyu @",
    "L  R#fuuuuuíuuyyywwwyyywwwyyyuu @",
    "L  @##íuuuuuuyywwwyyywwwyyíuuuu @",
    "@@C@@@@@@@@@@@@@@@@@@@@@@@@@@@@&@"
  ],"another level","Anonymous",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@óóóó            @@@@        á  í  @",
    "@+á@@ @@nnnnnn@@      @@@@@@ó@@ @@ @",
    "@áá   @ áíííííá@@@ @@@óóóó@@ó@e @@ @",
    "@í@@@ @ @nnnn@áe@@ @@   @óóóó@e@@@ @",
    "@ @@@   @####@@e@@ííáá@ @@@@@@e @@ @",
    "@ @@@óóó@@@@@@@e@@@óó@@ @@@@@@@ @@ @",
    "@            @@eáá @óóó         @@ @",
    "@&@@@@@@@@@  á@@@@ @@@@@á@@@@@@e@@ @",
    "@uúuuúuyy@é @ááá@@     @í@@www@e@@ @",
    "@w@@@@@@y@@ @@@á@@ @ @ @ @@w#w@e@@ @",
    "@w@      @    @á@@ @ @ @ @@w#w@e@@ @",
    "@w@ @@@@@@    @á@@ @ @ @ @@w#w@e@@ @",
    "@ó@     @@ ^@ó@á@@ @ @     w#w e@@ @",
    "ó  @@@@ @@ @@ó@á@@ @ @@@^@@@@@@@@@ @",
    "ó  áááá    @@óó    @               @",
    "@@C@@@@@@@^@@@@@@@p@@@@@@@@@@@@@@@i@"
  ],"maze","Anonymous",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
    "@   @   @   @        @ @ @ @ @   +@",
    "@ @   @   @ @ ######t@@@@@@@@@m@@@@",
    "@ @@@@@@@@@ @ #     @@@@@@@@@@@@@@@",
    "@ @         @         á   á   á  y@",
    "@ @;@@@@@@@@@p     iá á á á á á @y@",
    "@ @@ý@e  @@@@@#####@á   á   á   @y@",
    "@ @@ý@e@         @@@áááááááááááá@y@",
    "@ @@ý@e@@a#####@ @@@@@@@@@@@@@@@@y@",
    "@ @@ý@e@@@@@@@@@ @www@www@www@wwww@",
    "@ @@ý@e@         @w#w@w#w@w#w@w#@@@",
    "@ @@ý@e@ @@@@@@@@@w#w@w#w@w#w@w#@@@",
    "@ @@ý@e@ @   @   @w#w@w#w@w#w@w#@@@",
    "@ @  @e@ @ @ @ @ @w#w@w#w@w#w@w#@@@",
    "@ @@ @e@ @ @ @ @ @w#w@w#w@w#w@w#@@@",
    "@  @   @   @   @  w#w w#w w#w w#@@@",
    "@@C@@@@@@@@@@@@@@C@@@C@@@C@@@@@@@@@"
  ],"training level","Anonymous",
  [[{},"Feel free to add in another Lava to Solid Powerup"],
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "óóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóóó",
    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@óóóóó",
    "@@@@@@@@@@óóóóóóóóóóóóóóóóóóóóóóóóóóó@@@@@@@@@óóóóó",
    "@@@@@@@@@@óó@@@@@@@@@@@@@@@@@@@@@@@@óó       @óóóóó",
    "@@@@@@@@@@@ó@@@@@@@        eeeeeeee@@@      +@óóóóó",
    "@@@@@@@@@@@ó@@@@@@@        effffffe@@@      @@óóóóó",
    "@@@@@@@@@@@ó@@@@@@@        @@@@@@@e@@@ q    @@óóóóó",
    "@#########@ó@Luuuuuu       @@@@@LhhR@@ qqq  @@óóóóó",
    "@###eeee##@ó@@>eee<vw      @@@@@LuuR@@      @@óóóóó",
    "@##e    ee@ó@@#eeeR@w     p@@@@@LuuR@@ q  q @@óóóóó",
    "@#e       @óó@Leee#@w      @@@@@LuuR@@ qqqqq@@óóóóó",
    "@e  f^@ww#@@ó@#eeeR@w      @@@@@LuuR@@ qqqqq@@óóóóó",
    "@   #@@&ww@@ó@L   R@w      @@@@@LuuR@@ qq q @@óóóóó",
    "@   #@@ww#@@ó@L    Raw# # #@@@@@LuuR@@  qq  @@óóóóó",
    "@    @@&ww@@ó@L&  R@ww# # #@@@@@LuuR@@ q    @@óóóóó",
    "@^   @@www@@ó@L    Rww# # #@@@@@LuuR@@ qqqq @@óóóóó",
    "@#   @@w&w@@ó@L   R@ww#w#w#@@@@@LuuR@@ qq   @@óóóóó",
    "@    @@##w@@ó@L  &@@ww#w#w#@@@@@LuuR@@ qq   @@óóóóó",
    "@   ^@@www@@ó@L   R@ww# # úó@@@@LuuR@@ qqqq @@óóóóó",
    "@   #@@www@@ó@L    Rww# # #óó@@@LuuR@@   qq @@óóóóó",
    "@    @@w&w@@ó@L&  R@ww# # #@óó@@LuuR@@ qq q @@óóóóó",
    "@    @@w##@@ó@L    Rww# # #@@óó@LuuR@@  qq  @@óóóóó",
    "@^   @wwwwóóó@L   R@ww# # #@@@óóLuuR@@     p@@óóóóó",
    "@#   @ww##@@@@L  &@@ww# # #@@@@óL  R@@    p#@@óóóóó",
    "@    ú    @####   R@ww# # #@       R@@   p##@@óóóóó",
    "@    #   #L       #@ww# # #@maaa<  R## Ci###@@óóóóó",
    "@    #            #@a0#p#p#@@@@@@      #@@@@@@óóóóó",
    "@v^^^@Cv*<><>*v^BB@@@@@@@@@@@@@@@@@>####@@@@@@óóóóó"
  ],"Untitled-0 by Steven (Revised)","Ben",
  [[{"cpx":80,"cpy":80},"Hello world!"],
    "                                                     g                       @@@",
    "                                                     g+                      wwR",
    "                                                     ggggggggggggggggggggggggyy@",
    "                                                     ggggggggggggggggggggggggyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                                                                            gyy@",
    "                       úúú                                                  gyy@",
    "                       úúú                                                  gyy@",
    "                     ww@@@                                                  gyy@",
    "                     ww@@@                                                  gyy@",
    "                     ww @                                                   gyy@",
    "                     ww @@                                                  gyy@",
    "                     ww @@                                                  gyy@",
    "                     ww @@@          ó                                      gyy@",
    "s                    ww @@@@                                                gyy@",
    "syy      m;=f        ww @@@@                                                gyy@",
    "sww============      ww @@@@         d                                      gyy@",
    "swwwsssssssssss      ww @@@@         d                                      gyy@",
    "swwwssssswwwwww      ww @@@@@        d                                      gyy@",
    "sswsssssswwBBww      ww óóóóó        d                                      gyy@",
    "swwsssssswRwwLw      ww @@@@@        d                                      gyy@",
    "swwsssssswwwCww      ww @fff@ggggggggwwwwwww                                gyy@",
    "sw&sssssswwwwww      ww @aaa@gggggggg                                       gyy@",
    "sw sssssssssssssssssssssssesssss                                            gyy@",
    "sw sssssssssssssssssssssssesssss                                            gyy@",
    "sw                        esssss                                            gyy@",
    "sw                        esssss@@@@@@@@@@@@@                               gyy@",
    "sw                         *####@@@@@@@@@@@@@                               gyy@",
    "s&***<<<<<<<<<<<<<<<<<<<<< *####@@@@@@@@@@@@@                               gyy@",
    "ggggggggggggggggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
    "ggggggggggggggggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
    "ggggggggggggggggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
    "ggggggggggggggggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
    "ggggggggggggggggggggggggg*e*####@@@@@@@@@@@@@                               gyy@",
    "ggggggggggggggggggffggggg*e*####@@@@@@@@@@@@@                               gyy@",
    "@@@@@@@@@@@@@@@@@+@@#####*e*####@@@@@@@@@@@@@                               gyy@",
    "@wwwwwwwwwww   @@|@@#####*e*####@@@@@@@@@@@@@                               gyy@",
    "@wwwwwwwwwww ;  www@aaaaaae*####@@@@@@@@@@@@@                               gyy@",
    "@wwwwwwwwwwwww wwwwwwwwwwwe*####@@@@@@@@@@@@@                               gyy@",
    "@wwwwwwwwwwwwwwwwwwCaaaaaa**####@@@@@@@@@@@@@                                yy@",
    "@wwwwwwwwwwwwww@w@@@############@@@@@@@@@@@@@yyyy       p                    yy@",
    "@wwwwwwwwww;;**@@@@@############@@@@@@@@@@@@@gggg******************************@"
  ],"A level...","230141",
  // [[{"cpx":80,"cpy":80},"Hello world!"],
  //   "@@@@@@@@@@@@@@@@@+@@>>>>>>>",
  //   "@              @@w@@>>>>>>>",
  //   "@               www       >",
  //   "@   @===@       www       >",
  //   "@     #         wwwiiii  +>",
  //   "@     #        @w@@@>>>>>>>",
  //   "@@@@@@@@@@@@@@@@@@@@>>>>>>>"
  // ],"hiiii","hi",
  [[{"cpx":80,"cpy":80},"lava ahead!"],
    "@##@@@@@@@@@@@@@@+@@",
    "#        wwwww @@w@@",
    "+        wwwww  w@w@",
    "@##v#a=  wwwwi  w@w@",
    "@ @      wwwww  www@",
    "@        íííííh;Cp^@",
    "@B@@@@a>0@@@@@@@@@@@"
  ],"training level","sysdl132",
  [[{"cpx":80,"cpy":80},"flappyball","1","2","3","4","finish"],
    " #                #     #   #          +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #     #              +",
    " #                #         #          +",
    " f                          #          +",
    " @                          #          +",
    "+@      &                   #           ",
    "+@     &#               #   #           ",
    "+@    &##         #     #  ^#           ",
    "+@   &###        @@ 1 @@ 2@@ C3gg       ",
    "+@  &####a     @@#@hhCh            gg5 &",
    "+@@&#######v0vC###@###################gg"
  ],"flappyball changed","sysdl132",
  [[{},"answer 2 questions to pass!(confusion)","q1:1+1=?","left=2;right=4","q2:apple+penx2+pineapple=?","left=PPAP;right=I don't know.","you win!","null","null","null","correct!"],
    "@*******@",
    "@wuuuuuu@",
    "@wC01h2h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@@@h@h@",
    "@w@ óó@#@",
    "@w@ óó@#@",
    "@w@ 39@@@",
    "@w@     @",
    "@w@4hCh@@",
    "@w@@h@h@@",
    "@w@@h@h@@",
    "@w@@h@h@@",
    "@w@@h@h@@",
    "@w@óó@ff@",
    "@w@ó9@@@@",
    "@w@ó  @@@",
    "@w@@ C@@@",
    "@w@@    @",
    "@w@@a## @",
    "@w@     @",
    "@w@ ####@",
    "@w@    +@",
    "@&@5Cggv@"
  ],"questions for you!","sysdl132",
  [[{"SHEEPphys":"solid"},"welcome and watch out,if you want die,<<<","go down","go>>>(<<<checkpoint,next checkpoint 30 blocks away)","go up","<<<go","go down[!!!no more checkpoints!!!]","go down!!","jump!","<<<you win!","<<<"],
    "f@@@@@@@g@@@gggóóóóóóó      íg     ",
    "#      @ggg@g@gó@@@@@@@4á    g4h   ",
    "g      @g@g@gggó@@@@@@@      g     ",
    "g      @@@@@@@g       @   ááág  hh ",
    "g      ó    @@@       @      g     ",
    "gwwwwwww@@@  @@C56a## @áá    ghh   ",
    "gwwwwww@@@@o @@       @      g     ",
    "gw@1@@í@e##@ @@     97@á     g     ",
    "gw@@@@í@e#@@ @@       @ehhhó@gggggg",
    "gw@@@  @eú@@ @@       @e@@óó@gggagg",
    "gw@@@  @e@@@ @@ff+8fff@e@@ó^@gggggg",
    "gó@@@  @e@@@ @@@@@@@@@@e@@ó@@gg^ggg",
    "ó  áá   eíí        óó  e     gggggg",
    "`0C@@***@@@C2*@><@t@@@3@@@^@@gggggg"
  ],"level delier","132",
];
var loc=window.location.pathname.slice(window.location.pathname.lastIndexOf('/',window.location.pathname.lastIndexOf('/')-1),window.location.pathname.lastIndexOf('/'));
if (loc=="/platformre"||loc=="/maker") {
  var vroom="";
  for (var i=0;i<exampleLevels.length;i+=3) {
    vroom+='<li onclick="example('+(i/3)+');">'+exampleLevels[i+1]+' by '+exampleLevels[i+2]+'</li>';
  }
  document.querySelector("#EXAMPLES").innerHTML+=vroom;
}
try {
  if (!SHEEP.dismissed.platformreexplore) {
    SHEEP.dismiss('platformreexplore');
    SHEEP.notify('You can now play other people\'s levels!','/platformre/explore');
  }
} catch (e) {console.log(e);}
/* MADE BY SEAN */
