var blockData={
  "air":{
    "priority":0,
    "solid":false,
    "colour":"transparent",
    "xGravity":0,
    "yGravity":0.0109,
    "xDefaultVelocity":0,
    "yDefaultVelocity":0,
    "xMoveSpeed":0,
    "yMoveSpeed":0,
    "jumpVelocity":0,
    "xFriction":1,
    "yFriction":1
  },
  "solid":{
    "priority":1,
    "solid":true,
    "colour":"#212121",
    "lateralAcceleration":0.03,
    "jumpVelocity":0.2,
    "xFriction":0.8,
    "yFriction":0.8
  },
  "water":{
    "priority":2,
    "solid":false,
    "colour":"#2196F3",
    "xFrictionAmplifier":0.95,
    "yFrictionAmplifier":0.95
  }
};
